### ISSUE TITLE
Include body content in email templates

### ISSUE THREAD

**Issue by PlanetThoughts** [Simplero/Roadmap#10]
Since there are already email templates, one additional field could be added rather easily to the template definition, to hold default content for that template's body. The body content could be, as examples, layouts with one-column, two-columns, or a quote at the top and two columns. The editor in the template for the body field would use the standard WYSIWYG / HTML editor used in Simplero.

When preparing an email based on a template, the body content would be pre-populated with whatever was defined in the email template body.

**Comment by calvincorreli** [comment]
I did write up a comment, but must've not hit the button. Gah.

Anyway, not likely to implement. Adding the field to the templates isn't a big deal, of course, but currently nothing from the template is applied to the email itself, and we'd have to figure out when and how that happens.

What's the use-case here?

Seem like you could stick an email in the email library and click to send that as a broadcast. Not sure this would be useful for auto-responses, but then you could use automations and duplicate an existing email for this. Or just keep the content somewhere else (text editor, notepad) and copy-paste when you need it.

**Comment by PlanetThoughts** [comment]
Not to argue, but I will answer points you raise below.
 
* The use-case is that for a quick start, uses choose a template, and then
add content. In my experience with other email services, a template might
include a one-column layout, a two-column layout (to allow for an additional
announcement or content-type), and perhaps the same two layouts plus a quote
at the very top. So, when starting a new newsletter, one chooses one of
those templates and already have a good visual framework, such as column
widths, heading styles in each column, and other factors, pre-set.
 
The pre-set body text includes the layout HTML, but can also include the
salutation ("[Dear %FirstName%]" or whatever the format is for the token) as
well as the full signature.
 
Using Notepad seems a distraction from the flow and focus, but it is a
possible solution to something that seems like a logical feature of a
template, which is done that way in places like Constant Contact,
1ShoppingCart, and MailChimp.
 
You do apply fonts and colors from the template to the new emails, but I see
your point, none of the content is applied, so I can not be sure whether
that opens up a whole other "can of worms."
 
All that said, whether it is relatively easy or not, you may not want to
devote your resources to that when there are other priorities.
 
David Alexander
Insight and Energy Specialist
(718) 229-2609
 

  _____
