### ISSUE TITLE
Sort out disengaged contacts 

### ISSUE THREAD

**Issue by Lyv** [Simplero/Roadmap#106]
It would be great to have a way to quickly identify contacts who 1/ have never opened any broadcasts 2/ haven't opened broadcasts in x months 3/ haven't opened more than one specific number of broadcasts in x months.
Therefore I could send a re-engagement campaign to them. 
This could be done with segments, but with tens of broadcasts sent each month it can get pretty tedious...
Thank you

**Comment by calvincorreli** [comment]
Should be possible now with new filters on the tables. If not, definitely when we get to full conditional segments later.
