### ISSUE TITLE
Landingpages / salespages - Count down timer + redirect

### ISSUE THREAD

**Issue by ChristinaChristiansen** [Simplero/Roadmap#11]
1) would love to have a count-down timer on the salespages
(I know I can get the code externally and insert as html... ) But would be really nice

2) Would love to have the possibility to redirect
So that when you run a campaign you can set a timer on that page
After that time people should be redirected to another page

YES I would love not to be up aften 24:00 manually changing stuff :-) 
AND not to loose traffic from closed campaigns

Hope it makes sense

**Comment by calvincorreli** [comment]
This is a great idea. I'm on it!

**Comment by calvincorreli** [comment]
This has now been implemented and deployed to production. Enjoy!

**Comment by ChristinaChristiansen** [comment]
WAUUUUU thank you Calvin!
