### ISSUE TITLE
Stop autosaving on landing paging editing

### ISSUE THREAD

**Issue by drvitor** [Simplero/Roadmap#111]
We lost a lot of time when editing landing pages due to the autosaving whenever a single character is changed. Keep only that save button, please.

**Comment by calvincorreli** [comment]
How does it make you lose time? It shouldn't block you from continuing to edit. Is it that your computer cannot keep up with it?

It's been this way for years, and I haven't heard of anyone else having issues with it. I want to understand what the issue is.

**Comment by drvitor** [comment]
Every time it autosaves it has to wait the saving process to restore the
editing cursor alive. The solution I found is to use the code window
instead.

By the way, the main editing window is also too narrow.

Regards

**Comment by calvincorreli** [comment]
So when you're in the rich text field? I'll look into that.

There's a button up top to make the editor area wider.

**Comment by drvitor** [comment]
Yes. Thanks.

**Comment by calvincorreli** [comment]
I'm not seeing the problem. See here:

http://cloud.smpl.ro/232j0n3u0A15

What browser are you using?

**Comment by drvitor** [comment]
Thanks, I am able to widen the window. But the slowing of editing when
autosaving is there yet. (My computer is not slow and I use Chrome.)

Regards

**Comment by calvincorreli** [comment]
Just tried in Chrome. I'm still not seeing a problem, and I can't fix a problem I don't understand.

Can you help me understand exactly what you're doing? Are you doing the exact same thing that I just showed in the video above? Then maybe there's an extension or something interfering? Even when the network is slow, I'm not in any way prevented from continuing to edit. Nothing is frozen or locked for me.

So the question is, what's going on on your computer? Can you shoot a video to show me?

**Comment by drvitor** [comment]
It may be my computer actually. When the saving green bar above is running,
I cannot edit. I have to wait the saving process.

Thanks, I will try later on another computer.

Regards.

**Comment by calvincorreli** [comment]
New landing pages implemented.
