### ISSUE TITLE
Automations: Enable the ability to delay based on a date field within a person's profile

### ISSUE THREAD

**Issue by ellentmc** [Simplero/Roadmap#112]
We'd like to be able to trigger an automation weekly, monthly, annually based on a field timer - e.g. send an email on a person's birthday. This is the kind of delay we would use quite frequently.

**Comment by calvincorreli** [comment]
This is on the roadmap, for sure.

**Comment by themanagementcoach** [comment]
Would love to know when this feature might be getting enabled. I keep seeing fun little enhancements like "Global Snippets" come out, but this one just seems so much more important than that! Date fields allow me to automate notifications for so many things related to connecting me closer with my clients... birthdates, anniversaries, program milestones that are not tied to their product dates necessarily...

**Comment by calvincorreli** [comment]
we implemented this a while ago.
