### ISSUE TITLE
Default or remembered view and sort order for Lists & Contacts

### ISSUE THREAD

**Issue by PlanetThoughts** [Simplero/Roadmap#115]
In the Lists & Contacts area, the user always starts from either "All" or "Active". It would be good to allow customizing those views to have the columns the user wants. Or, if not that, it would be good to be able to define a custom view for use with all lists as well as with Contacts, and then make that the default view. The default view as well as the default order should be remembered for a given user. Otherwise, for example, if I want to see all Contacts sorted by most recently joined, I have to click sort twice on the Added column. On other screens, if I want to sort by last name, I have to go to a custom view previously defined, then click twice on the last name column. If those are the views I always use, I should be able to make those the default (custom or regular) view and default sort order.

**Comment by PlanetThoughts** [comment]
It would be nice to have the same feature for other sortable displays, such as Products, Media files, etc. In some cases the view might the current default, but a sort order would be pre-set. In other cases, the user might define a custom view and make that the default view, as well as having a default sort order.

**Comment by nickbruun** [comment]
If you select a different sort order, you can save that as a custom view. What is the particular issue here?

**Comment by PlanetThoughts** [comment]
Thank you for asking. You should try it (if you have not). From what I have found, each time I come to Broadcasts, I need to close the Queued filter option, then choose my own custom view, click on Date Created column to sort in ascending order, and click Date Created a second time to get descending order and see the broadcast I have most recently created, which is where I want to go 90% of the time. This happens multiple times per day when I am preparing a broadcast, and seems avoidable. Am I missing something? TIA.
--

**Comment by nickbruun** [comment]
I just tried it, and when I do it the sort order of the columns is saved with the custom view. Can I have you submit a ticket regarding the specific views where you're having issues?

**Comment by PlanetThoughts** [comment]
Ok, will do it when I am at computer (not cell phone) again.
--
