### ISSUE TITLE
Evergreen Countdowns in Simplero

### ISSUE THREAD

**Issue by lrt-danielat** [Simplero/Roadmap#120]
I know that you have a countdown timer for landing pages where you can add an expiry date.

What would be very cool for us, would be countdown timers that we can use on sales pages, order pages, e-mails etc.  We're planning to build an evergreen sales funnel, where we don't need to manually change the countdown.  We should be able to configure it in such a way that we don't need to update it.

I'm thinking of it as a personalized deadline for each contact. I've seen this in other marketing systems.

Are you planning to build something like that? Do you have an integration with some other software?

Thank you,
Dani

**Comment by calvincorreli** [comment]
It sounds like a deceptive marketing practice, and not the kind of thing we'd want to support.
