### ISSUE TITLE
Sort the e-mail list under each contact  - the newest first

### ISSUE THREAD

**Issue by Annebente** [Simplero/Roadmap#121]
For each contact we can see all e-mails that has been sent. But the oldest is in front, ant most often we are looking for the newest e-mail.

(simplero.com/admin/customers/customerID)

It would be great if we could sort the list so that the newest e-mails is in front. The old e-mails are not so interesting.

Hope this is possible. 
Thanks :)

**Comment by calvincorreli** [comment]
That's a good point. Looking at the code that was actually what it was supposed to, but because if a typo, that didn't happen. I've fixed that now.
