### ISSUE TITLE
NEW MEMBERSHIP REQUESTS

### ISSUE THREAD

**Issue by JamesGordonGraham** [Simplero/Roadmap#124]
Hi Calvin, Nick
I'll try to embed this wistia video here which is designed to give you some feedback on the old Spaces v new Membership site
If it does not work I can put it onto the Facebook page?

<script src="https://fast.wistia.com/embed/medias/5yz1pqh4ex.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_5yz1pqh4ex videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>

James Graham

**Comment by nickbruun** [comment]
Hi James,

Thank you for the feedback. Could I have you break it up into separate issues with a detailed explanation/motivation so others can participate in the discussion?

Best,
Nick

**Comment by JamesGordonGraham** [comment]
Hi Nick
Yes, I can do that for you

Best
James

**Comment by nickbruun** [comment]
Hi James,

Cool. I'll close this issue then :)

Nick

**Comment by JamesGordonGraham** [comment]
Nick - I had not realised you had opened a ticket for this video.

The reason I did a video was because it takes so much time for me to write
things out fully.

In summary my requests are to;
1. have pull downs from the Couse module, Blogs and Forum areas of the
MEMBERSHIP SITE.
2. to have a Hero/Header at the top of the Couse module, Blogs and Forum
areas of the MEMBERSHIP SITE
3. that the first text above the modules is clickable
4. that you incorporate a 'Worksheet' button under the Quiz
5. that you provide navigation buttons at the bottom of a course.
6. have the side navigation coming down with the scrolling on a long course
module
7. that the Theme allows you to automatically size the full text and
graphics from the desktop to the iphone/cell phone
8. that you do not have the sidebar overlapping the hero header on the
PAGES section

Also not sure how you delete a membership site?

best
James

**Comment by nickbruun** [comment]
James, can I have you elaborate on the following?

1. What do you mean by pull downs?
2. Are you referring to having a hero image for the entire membership site?
3. I'm not sure what this "first text" is? Can you 
4. What's the scenario where having a worksheet for a quiz makes sense?
5. There is already navigation between lessons at the bottom of a lesson
6. Often-times the side navigation will be so long that you'll have to scroll all the way to the top to make sure this works 
7. I'm not sure I understand what you mean by "that the Theme allows you to automatically size the full text and graphics from the desktop to the iphone/cell phone"

**Comment by JamesGordonGraham** [comment]
Hi Nick
1. Pulldowns - If you look at 'Your Spaces' (within the Membership site
menu) it has an arrow facing down. If you click on this you get a choice of
options - this is what I mean by a pulldown.
2 At the moment I do not understand how to put a hero/header on top of the
a. courses, b. blog or c. forum.
3 You need to refer to the video where I point this out
4 No, I don't mean that. I mean that you need to put the worksheet link
under the course so it sits as a third option. The quiz and lesson being
the first two options.
5 When you get to the bottom of a long course module there is no navigation
at the bottom of the page. (see video). It is tedious for a customer to
have to scroll back to the top of the page to reconnect with some
navigation options.
6 Same as above (5). Perhaps you can design the side module to stay with
you no matter how long the course is?
7 When you put the course on an iphone the graphics do not seem to size
properly. It needs to be done automatically.
There is one more
8 You need to give us an ability to size text.

Thanks

**Comment by nickbruun** [comment]
Hi James,

I unfortunately cannot refer back to the video right now as it's for some reason no longer working. Could you please provide a link to the video on something like YouTube where we can access it?

**Comment by JamesGordonGraham** [comment]
Hi Nick
I've uploaded the video to youtube
https://youtu.be/9_vdGOwqnyw

Another glitch you might like to look at is
- when you are editing text, if you hit a return to create a new paragraph
that includes some text, it copies the whole text twice?
best, James
