### ISSUE TITLE
Add LinkedIn and LinkedIn Group buttons to Membership Site social media settings

### ISSUE THREAD

**Issue by themanagementcoach** [Simplero/Roadmap#126]
It would be good to be able to add a link to my LinkedIn group and LinkedIn profile on my membership site alongside the other social media buttons.

**Comment by nickbruun** [comment]
Are you referring to the links in the lower right hand side corner?

**Comment by themanagementcoach** [comment]
Yes, those are the ones. :)



Mary Legakis Engel
The Management Coach
Tel: 647.985.9358
www.themanagementcoach.com

   - ca.linkedin.com/in/marylegakis/




IMPORTANT NOTICE: This email and the information contained herein is
confidential and is intended only for the use of the person to which it is
addressed. If you are not the intended recipient you are hereby notified
that any disclosure, distribution or copying of this communication is
strictly prohibited. If you have received this communication in error,
please notify me immediately by email or phone. Thank you for your
cooperation.

**Comment by nickbruun** [comment]
What does a link to a LinkedIn group look like? Do you have an example of that?

**Comment by themanagementcoach** [comment]
Attached screen shot, top right corner - this is the version on their
website.
The img file is the version they use for the iOS app.



Mary Legakis Engel
The Management Coach
Tel: 647.985.9358
www.themanagementcoach.com

   - ca.linkedin.com/in/marylegakis/




IMPORTANT NOTICE: This email and the information contained herein is
confidential and is intended only for the use of the person to which it is
addressed. If you are not the intended recipient you are hereby notified
that any disclosure, distribution or copying of this communication is
strictly prohibited. If you have received this communication in error,
please notify me immediately by email or phone. Thank you for your
cooperation.

**Comment by nickbruun** [comment]
Screenshots do not seem to show up here. Can I have you try replying on GitHub instead of an email?

**Comment by themanagementcoach** [comment]
![img_3193](https://user-images.githubusercontent.com/32145688/31106516-2b7c4f9a-a7ba-11e7-90ae-67e0933dbb29.jpg)
![screen shot 2017-10-02 at 7 16 18 pm](https://user-images.githubusercontent.com/32145688/31106521-31ea526e-a7ba-11e7-95b9-848280b10b8e.png)

**Comment by nickbruun** [comment]
Thank you for that. Do you have an example of what link to a Group could be?

**Comment by themanagementcoach** [comment]
https://www.linkedin.com/groups/5176892

**Comment by calvincorreli** [comment]
LinkedIn is now included in the options. Thank you for your patience.

Is the link to a linkedin group still relevant?

Would it be one group, alongside the profile?

Or multiple groups?

What's the icon that we'd use for that? Same as for the linkedin profile ("in" icon?
