### ISSUE TITLE
Enable Downloads of Media files on a Per-Product Basis

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#132]
Feature request: 

An option on Products, to make it possible to have two products sharing one Membership Site, and have media download access allowed for members who purcase product A (the full version) but disable downloads for Product B (cheaper product).

I am aware that downloads can be disabled throughout the refund period of a product, but am looking for a permanent "switch" on a product to allow/disallow downloads.

Of course there's the situation where the product allows downloads but the Membership Site (or space) doesn't allow downloads: In that situation it makes sense for me to let the Membership Site / Space setting overrule the product setting.

I have this situation currently, and a feature like this would allow me to merge two otherwise identical Spaces into one single Membership Site. It would save me a lot of work keeping the two spaces in sync.

**Comment by nickbruun** [comment]
This is a great idea. I've implemented it now, so you can stop having to do twice the work :)

If you go to the _Content_ section of the settings for a product, under _Content access_ you can now prevent downloads across all membership sites (and spaces) and any content files attached directly to the product.
