### ISSUE TITLE
Worksheet printing 

### ISSUE THREAD

**Issue by ManjirS** [Simplero/Roadmap#136]
Worksheets used to look fab when printed. The new features are great but now when they are printed they look terrible - see screenshot. 
I would like to have people be able to print off a worksheet whilst doing the workshop with me so they don't have to keep switching between windows. 

But the way they look now is bad and the logo is far too big. The reason why I moved to Simplero from Jigsawbox was the addition of worksheets and although the online version is great, the printed ones are important too. 
Thanks

![bitmoji](https://render.bitstrips.com/v2/cpanel/9853623-118315790_13-s1-v1.png?transparent=1&palette=1&width=246)

![screen shot 2017-10-10 at 18 17 24](https://user-images.githubusercontent.com/28048176/31401462-d768381a-adea-11e7-90e5-3241f97f86be.png)

**Comment by nickbruun** [comment]
This is definitely an unintended consequence of the upgrade. Looks like we forgot to bring over some print-related styling. Ooops. I'm deploying a fix this second :) Thanks for the heads up!

**Comment by ManjirS** [comment]
Thanks so much. That was quick. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/8298890-118315790_13-s1-v1.png?transparent=1&palette=1&width=246)
