### ISSUE TITLE
Editing a contact automatically fills in blank State and Country fields with incorrect information

### ISSUE THREAD

**Issue by themanagementcoach** [Simplero/Roadmap#139]
I have set up my fields to include a Primary and Secondary address for my clients. When the Secondary address fields are empty, clicking on "Edit" automatically populates the State field with AB (Alberta) and the Country field with Canada, every time.

It would be good if these fields could remain blank unless they have been intentionally filled in by someone.

**Comment by calvincorreli** [comment]
Fixed now. Thank you for your patience and support!
