### ISSUE TITLE
Membersite . functionalities

### ISSUE THREAD

**Issue by ChristinaChristiansen** [Simplero/Roadmap#140]
Please see this video
https://www.facebook.com/groups/simplerousers/permalink/1495862373826228/

Full integration between product catalogue and actual membersite - so that some video's can be seen others not - but the lesson overview is available. 

Featuring of courses on main menu with slidebars

Credits - different membership levels gives X number of credits, and each month a member get X amount of credits to buy for...  On their account it is visible how many credits left and how to buy more.

Catagorization by topic and search function - (Metatags on courses)

"Watch lists" 

please see the video too

**Comment by nickbruun** [comment]
Hi Christina,

Those seem like some really great suggestions. However, large requests with multiple different things in them like these are somewhat unmanagable for us and hard for others to find in the overview, so I've written up a few guidelines for requests.

I'd love it if you could break this request down into individual requests for each of them, so everyone can clearly see that a specific feature is requested and participate in the discussion around it. I'd love to not have any confusion around whether we're talking about the "credits" idea or search functionality when there is a conversation in here. Further to that, videos are really hard to quickly scan through, so suggestions like "Watch lists" don't actually offer much in the way of anyone else knowing if that's what they're requesting too.

Thank you for your suggestions. However, I'm going to close this one out and can't wait to start the conversation about the individual requests you have when you've submitted them :)

Best,
Nick
