### ISSUE TITLE
Feature request: an overview page type in membership sites displaying all available courses

### ISSUE THREAD

**Issue by infospray** [Simplero/Roadmap#144]
Right now all courses (that a customer has access to) are displayed in the menu (they can be removed though).

However if there are more than a couple courses, the menu quickly become crowded. 

My first solution was to create a custom page and simply list all the courses. 

However, this will display ALL courses, including those my customers haven't purchased yet. 

So a better solution would be to have some kind of overview page where all courses (inside a given membership site)  that the customer has access to, is displayed.

Thanks.

**Comment by nickbruun** [comment]
This seems to be a very common need, and I totally get it. So, I've added a new type of section you can add to a page: a course catalog. This will list all the courses a member has access to on a given membership site in a layout akin to how the product catalog is listed.

I hope this solves your problem :)

**Comment by infospray** [comment]
THANK YOU.

One small thing. What is the sorting of this view? Currently it looks like it's in the order of creation. 

I'm not really looking to ordering the courses, but having them sorted alphabetically would be a great start
