### ISSUE TITLE
Facebook share image for old-skool landing page

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#146]
In the new pages you can chose a picture that will show on Facebook or other social platforms when shared there. But in the old landing pages you cannot do that, which means the page sometimes looks awful when sharing it on Facebook ... 

it would be wonderful if the old landing pages could have the same sharing feature as the new pages

**Comment by calvincorreli** [comment]
Please don't use all-caps for the title.

**Comment by ingjerd123** [comment]
Alright, I'll be better ...

**Comment by calvincorreli** [comment]
We're focusing on new themed landing pages. Closing this now.
