### ISSUE TITLE
Trigger option in list

### ISSUE THREAD

**Issue by sherrieanne** [Simplero/Roadmap#15]
It would be nice to have a trigger option in a list that was anytime someone subscribes and not just first time activation

**Comment by calvincorreli** [comment]
The current trigger runs each time someone subscribes, not just the first time.

If they're already subscribed, it does nothing.

**Comment by sherrieanne** [comment]
Right we want the ability to choose to run the trigger even if they are already subscribed.

**Comment by calvincorreli** [comment]
Okay. First time activation (for participant, for example) means something else.

In Simplero internally, subscribing when already subscribed is not an event. Nothing happens. Nothing changes.

What's the use-case here? What are you trying to accomplish?

**Comment by sherrieanne** [comment]
sorryI was updating the comment while you were replying. same idea as the autoresponder request. Say someone has an opt-in like a quiz where people may fill it out more then once. but never unsubscribe from the list in between but the account owner still wants them to have the autoresponders each time they subscribe.

**Comment by calvincorreli** [comment]
Implemented and deployed now.
