### ISSUE TITLE
Aligning video display with lesson title for viewing on computer

### ISSUE THREAD

**Issue by CoachWouter** [Simplero/Roadmap#152]
Hi Nick,
What can you do to help us align the lesson title with the video display for Mac and PC viewers. I understand that the alignment for video is now centered and the lesson title left. The attached screenshot shows the issue. I appreciate that it all looks good already on mobile and tablet, however it looks awkward on Mac. 
Thanks!
Wouter

<img width="1280" alt="screen shot 2017-10-17 at 1 49 07 pm" src="https://user-images.githubusercontent.com/27732151/31710233-979e05a4-b41e-11e7-9ba3-26cf86e32aca.png">
![image](https://user-images.githubusercontent.com/27732151/31710290-bdf0ccaa-b41e-11e7-97ce-46b7da2e9b30.png)

**Comment by nickbruun** [comment]
The video is now full width so that should take care of it :)

**Comment by CoachWouter** [comment]
Hi Nick,

Thanks a lot! The video now aligns nicely with the lesson title on my Mac!

Kind regards,

Wouter
