### ISSUE TITLE
Ability to add a front 'welcome' page to my course

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#153]
In spaces, I can add a video or image to the welcome page when my clients log in - in courses, there's no way to do this - looks very 'cold' - I would like to be able to create a welcome page where I can add content/images etc, drop in the content headings (as you can already see here), or simply add a 'get started button' which would take them to the page you can see here.

In other membership platforms you are able to set a) page user lands on when they first log in and b) page user lands on on subsequent log ins - this would be great.

See how much more 'human' current spaces are 

https://www.dropbox.com/s/vfgt5et1444jn6p/Screenshot%202017-10-18%2014.10.57.png?dl=0

compared to the same program using courses

https://www.dropbox.com/s/gvqvgyu3mgu4y3s/Screenshot%202017-10-18%2014.07.31.png?dl=0

**Comment by nicolabird** [comment]
For example, see how much nicer my program looks if I design it in pages - much cleaner

https://www.dropbox.com/s/ga4fpknbxnj7j1r/Screenshot%202017-10-18%2014.24.28.png?dl=0

https://www.dropbox.com/s/agy4vnw2dvnvv53/Screenshot%202017-10-18%2014.25.14.png?dl=0

**Comment by nickbruun** [comment]
You can indeed add a description by simply going to the Course in your administrative interface and editing the settings for the course. The same goes for individual modules. Does this not cover the need you're describing here?

**Comment by nicolabird** [comment]
Great, that's perfect - sorry did not know that existed!
