### ISSUE TITLE
Resend Autoresponders

### ISSUE THREAD

**Issue by sherrieanne** [Simplero/Roadmap#16]
The ability to resend autoresponders no matter how many times someone subscribers even if they haven't unsubscribed in between. Example if someone has an opt-in for say like a quiz and they want them to get the autro responder no matter how many times the fill out the quiz.

**Comment by calvincorreli** [comment]
There's now an action to restart auto-responses for a subscription, so they'll be delivered again, starting now. You can use that in the new "attempted to subscribe" trigger to achieve this.
