### ISSUE TITLE
Worksheet trigger to access next course module in membership site

### ISSUE THREAD

**Issue by CoachWouter** [Simplero/Roadmap#160]
Hi Nick,

In my course Work In All Colors, there is an assignment at the end of each module, and receipt of response will trigger access to the next module. To streamline that process, I'm looking for ways to either:

1. include a link in the worksheet confirmation page to access the next module right away (I could not get this to work yet using the insert or hyperlink functions in the editing menu), or

2. seeing the course window auto-refreshed right away to show the next module that becomes accessible (now my user has to go back to the course window from the confirmation page and then press refresh in order to see the next module pop up in the curriculum.

Let me know what's possible?

Kind regards,
Wouter

**Comment by jonasnapier** [comment]
I think you can do this already

Add the next module as a confirmation page and set at trigger to make it accessible.
