### ISSUE TITLE
Membership Suggestions

### ISSUE THREAD

**Issue by acosta07** [Simplero/Roadmap#164]
Hi,

I have some suggestions about Membership sites:
1) Customization of the sidebar: the ability to change the position (left or right). And put customized content there.

2) We can put videos using 2 ways (media asset and additional content>media files) but using additional content it let the name of the file. So the ability to put the video (media asset) after content should be nice. 

3) Create an option to auto-complete lesson after watching a video and auto move forward.

Thanks so much!

**Comment by calvincorreli** [comment]
Doing a triage of feature requests...

"Membership Suggestions" is not a terribly helpful title. 

Please read the submission guidelines and try again:

https://help.simplero.com/categories/274166
