### ISSUE TITLE
Why I think that the “Members” feature in membership sites shouldn´t show previous members

### ISSUE THREAD

**Issue by JesperChristophersen** [Simplero/Roadmap#166]
Hi

A few days ago, I asked the following in a ticket about the “members” section on the new membership sites:

_In the “Members” section, Nick Bruun appears on the list as a member since September 30 2017. I imagine, that is because he visited the membership site on that day, but will everyone who visited the membership site stay on list forever?_

And Deanna kindly answered me this:

_Yes, Nick (or myself or Merete) would show up as member of the site when we visit because we have access to the Site/Spaces Anyone who access the site/space will also show up. We don't want to hide previous members as they might have written comments etc. So, if you wish to not have a member shown, you have to go to that member in the admin interface and delete it. (Ex: https://kunstner-anne-juul.simplero.com/admin/sites/13957/members/6400-deanna-buoniconti )_ 

Now – I have given this some thought:

Since it says “Members” in the navigation menu – I would expect it to only show current members and not former members, even if those previous members have written comments on the site.
I have just checked our spaces – and in the spaces, the “Members” section appears to only show current members – not former members, as far as I can see – and that really makes much more sense to me.

Also: I´m pretty sure that quite many of our former members would find it somewhat intimidating to still show as "members" - even years after they have cancelled their subscription.

As a former customer / member of something– I myself would definitely not want to still be listed as a current member on such a list of members, after my cancellation - of many different reasons, depending on the character of the membership.

Also – if former members appear as current members, we might have current members writing to or referring to former members in comments on the site, expecting the former members to be reading along – maybe even reacting – without them being able to even see what is going on, because they´re in fact not members anymore.

Would it be possible to make the “Members” section for membership sites like it is in spaces – showing only current members, - and then maybe – if you want it to be an option - add another possible section called “People who have written comments” or something like that – which could then be added – just like the “Members” section can be added to the navigation menu now?

That would make it possible for us to have the “Members” section just like we have now in our spaces – and those Simplero users who want previous members to also be shown, can choose to have that in their menu.

All the best
Jesper :)

**Comment by nickbruun** [comment]
So, after actually investing brain power into this, we all agree that you are completely right :) The behavior has now been changed to match that of spaces :)

**Comment by JesperChristophersen** [comment]
Awesomesauce 💃 Thank you so much. 👍
