### ISSUE TITLE
Membersite - full integration between products & membersite

### ISSUE THREAD

**Issue by ChristinaChristiansen** [Simplero/Roadmap#169]
I would love a full integration between products for sale and membersite.

So that you simply set op which sections (introductions + lesson overview typically) that should be viewable for all, and which only for people that have purchased. 

when a client has not yet bought the course - there should be at "buy now" button... and that should disapear when the customer has bought the course... 

That way upsell will be natural, and the potential clients get at great overview of what they can get and learn. 

Great example on tech solution is in Creativebug.com - see the first minuts on this video  
0 min to 0:55 & 2:58-3:33
https://www.facebook.com/groups/simplerousers/permalink/1495862373826228/

It would be great in the setting to be able to offer both

"All access passes" 
"Acces to individual courses"

**Comment by SaninaKurstein** [comment]
Hi 
Me too. Especially I would love if new members (sign up`s) could have acces  to free content and some paid ...
All the best Sanina

**Comment by janejacksoncareers** [comment]
Yes - that would be great too! Thank you. Jane

**Comment by desireeeast** [comment]
This would be wonderful...thank you!! :)

**Comment by calvincorreli** [comment]
We implemented this last year, just never closed this feature request.

You can now show a preview for your courses and link to where they can purchase it.

If there's anything about this feature you need help with, please talk to support. If there's anything about it that you need that we didn't include, please open a new feature request for that part.

Thank you for your suggestion.
