### ISSUE TITLE
Ability to create segments with AND

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#170]
If I want to create a segment with people who have this tag AND this tag, or this tag AND this product, I can't do that with segments.

Eg if I want to see the number of people that were tagged entering a certain automation then see how many bought, I currently have to 

Include 'tag' 'Received launch of product'
Exclude 'tag' 'Buyer 12 week program'

Then I have to manually subtract the number of contacts showing from the number that received the tag to work out how successful my launch was.

Currently I can do a segment on people who have this tag and people who have that tag but not find people who only have both. Unless I'm missing another way to find this?

**Comment by calvincorreli** [comment]
On the roadmap. Closing here.
