### ISSUE TITLE
a way to mass delete contacts

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#176]
I have 20,000+ contacts, having done a clean out around 13,000 of these are good quality leads I'd like to keep - and I'd like to just delete the rest - they are from old businesses and projects I've run in the past.

I can't see an easy way to do this so would love this feature (unless you already have it and I haven't found it?)

**Comment by calvincorreli** [comment]
There's now an option to delete unused/inactive contacts. Go to Contacts, click the Cleanup button top-right, and click "Delete inactive contacts".

Does this do it for you?

If not, reopen or submit a new feature request with more details.
