### ISSUE TITLE
Somewhat urgent: Move coupon code field to Your Payment section of Order Form

### ISSUE THREAD

**Issue by themanagementcoach** [Simplero/Roadmap#179]
My clients are having trouble finding the Coupon Code field because it is in the Billing Address section of the order form. If their address pre-populates then they aren't looking at that section. Since it's not typical for a coupon code to appear in the billing address section of a form, they aren't seeing it.

The coupon code field might better be placed in the "Your Payment" section, with instructional text as per the attached image.

![screen shot 2017-11-06 at 8 25 36 am](https://user-images.githubusercontent.com/32145688/32443332-9f9b06fa-c2cc-11e7-9a78-765d2a268b64.png)

**Comment by calvincorreli** [comment]
This should be deployed later today.
