### ISSUE TITLE
Flexibility to edit the auto generated text on order forms

### ISSUE THREAD

**Issue by JesperChristophersen** [Simplero/Roadmap#181]
When I make a price with six months commitment, Simplero automatically generates a text on the order form – saying something like:

_Product name – 6 months membership will be renewed every 6 months at (price) from (date). Cancel at any time after xx/xx-20xx._

Here´s a link to our order form as an example:
https://kunstner-anne-juul.simplero.com/purchase/38172-Kunstskolen-Annes-Atelier-6-maaneders

It would be very nice for us to be able to edit this automated text because:

1. In Danish the text “every 6 months” is translated to “hver 6 måneder”. It should say “hver sjette måned” or “hver 6. måned”.

2. Our price for 6 months commitment is paid in six small rates – one each month, but on the automated text it just says, that after the first six months period, the membership will be renewed at the full price for six months, - which indicates, that after the first six month, the price will no longer be split into small monthly payments, which can scare some customers off.

3. This is the most important issue for us:
We are okay with our customers asking us to cancel their membership by the end of the commitment of six months – before the six months have passed. They just email us, asking us to cancel the membership by the end of the six months commitment and we do that for them. In fact – we prefer having our customers emailing us to cancel their membership, instead of just clicking a button, as that opens up for a dialogue with them, which is great.

It just doesn’t make sense, that the automatically generated text on the order form says, that the customer can only ask for cancellation of the membership after the commitment period of six months has passed. At that point, the membership will have already been renewed. This signals to the customers, that there is no way out for a looong time, and that is of course not how it is. This can again unnecessarily scare customers off - just before they choose to buy our product.

The order forms are a vital part of selling the products and we would love to be able to edit these texts on our order forms, so they actually fit the descriptions of what we offer. No need to signal on our order forms, that we are stricter than we actually are. :)

**Comment by calvincorreli** [comment]
Hi Jesper, thank you for the request.

I've made some changes to the wording of the subscriptions and installment plans on the checkout screen. Would you mind checking if it's better now, or still has room for improvement?

As for the others, I'd love it if you'd open separate issues for them. It's really hard to navigate long mixed-up feature requests. It requires that we all read the entirety every single time we triage and go through to make decisions on what to implement and when.

As for commitment, you should generally set that to right after the last committed period ends, but if you can submit a new feature request with a link where I can see it, I can take a look.

Going to close this one.

–Calvin
