### ISSUE TITLE
Discussion Forums: Migration from Spaces to Membership Sites

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#186]
It would be much appreciated if it can be made possible to migrate / copy an existing Discussion Forum from a Space to a Membership Site, including all posts and user-generated comments.

Discussion forums is a rather structured and well-defined piece of content.

I am fully aware that migration of other content to Membership Sites in general is a manual process, but i would really love to keep the discussion forum intact and not loose all content in there.

Cheers,
Tue

**Comment by AndreaSchroeder77** [comment]
Agreed. I have some members of my site who have been there for four years - I don't want them to lose everything they have shared as we move to the new space.

**Comment by calvincorreli** [comment]
You can keep using Spaces, we have no plans to remove those, but obviously new development is going to be focusing on membership sites.

**Comment by calvincorreli** [comment]
Also, we do have migration from spaces to sites on the roadmap.

**Comment by tueolesen** [comment]
Good. I want to migrate my existing members from using a space to a membership site. Getting lots of positive feedback from them about the new look of the content, and the way that the course structure makes navigation easy.

**Comment by calvincorreli** [comment]
Glad to hear they like it! Hope we can make the migration happen soon!

**Comment by tueolesen** [comment]
Is this still in the plans, so we can expect a Forum Migration within the near future?

**Comment by tueolesen** [comment]
Just wanted to say "still interested". I've currently got my users navigating back and forth between a membership site for the main part of their content, and a space for the forum, for a while now.

It would be a big boost to migrate that old forum including all posts, to the membership site, allowing users to keep discussions inside the membership site.

These days #deletefacebook is becoming more of a big thing, and like mentioned earlier / elsewhere, a well-working, active forum will most likely benefit customer retention.

Looking forward to see this happen!

**Comment by JesperChristophersen** [comment]
#metoo

**Comment by tueolesen** [comment]
Forum Migration from Spaces to Membership sites  - how is it going?

This has been sitting on the roadmap since...many months. What's status these days, will it ever happen? Is it still worth to wait for, while we keep that part of our membership sites "locked in the past"?

Thanks in advance for any updates!

**Comment by tueolesen** [comment]
OK, thanks for the honest answer - better to know than to wait ;-)

**Comment by calvincorreli** [comment]
FYI, we've put this on our agenda for the next 6 weeks. That is NOT a promise, but just letting you know that we do intend to tackle this now.

**Comment by JesperChristophersen** [comment]
Awesome - thanks a lot for letting us know. 👍

**Comment by tueolesen** [comment]
Thank you @calvincorreli + TEAM for taking this up again - much appreciated (y)
-Tue

**Comment by tueolesen** [comment]
@calvincorreli any news on how things are going with Forum Migration?

**Comment by calvincorreli** [comment]
We haven't gotten to it yet. Haven't given up, though.

**Comment by tueolesen** [comment]
I've moved over manually. Finally gave in....or lost patience :-)

**Comment by JesperChristophersen** [comment]
Tue: Cool, I didn´t know that was possible, - how did you manage to move a forum manually from at space to a membership site?

**Comment by tueolesen** [comment]
Copy/pasted the most important posts (including replies) from the old forum on the space, to the new one. Lots of manual work, and it only solves the move around maybe 90% of the way. Post 

Dates and authors don't transfer, but at least the post content gets transferred.

Totally manual work. Not fun but i'd waited long enough....

**Comment by AndreaSchroeder77** [comment]
I did the same with the comments on my classes - it’s a long job but the questions and discussions in the comments sections are an important part of the lesson.

**Comment by JesperChristophersen** [comment]
Ahh okay, thanks. :) I still have my fingers crossed for a migration solution - so we can include authors and dates.
