### ISSUE TITLE
Pre Sale / begin next subscription on a fixed date

### ISSUE THREAD

**Issue by jonasnapier** [Simplero/Roadmap#187]
I would like to be able to pre sell a subscription.

**pre order and get a free month**

Course launch february 1st. 
So anyone who pre orders before that will pay 249,- now 
february has been pre paid 
march is free 
and then the next payment is april 1st (249) and then every month

One way to do this could be to have the first subscription period run untill a certain date.

**Comment by Siiffloor** [comment]
Oh my.. I have spent hours to figure out what I was doing wrong, because I could not get the payments, subscription and next payment to add up. Because my course has not started yet.

It dit not even occur to me, that this would not be possible.

**Comment by jonasnapier** [comment]
I think it should be made possible.

There is an automation function that allows you to wait untill a certain date. I image that linking this to a subscription period should be fairly easy.

But then again I don't knoe much (or anything actually) about how this works down in the "engine room"

**Comment by mortenspindler** [comment]
This feature is a MUST, we have this and use it a lot in a booking software, where a membership starts on a specific date and always runs from the 1st, I/we would very much like this feature.

**Comment by ChiaraSofia** [comment]
Oooh yes - this would be fantastic <3

**Comment by VibeBendix** [comment]
Would be so great :-)

**Comment by calvincorreli** [comment]
Just a heads-up that this is very close to being released ...

**Comment by jonasnapier** [comment]
Awesome

**Comment by calvincorreli** [comment]
This is out now.
