### ISSUE TITLE
Featured Courses - similar to Featured Products in Membership Sites

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#191]
The Course Catalog section for Membership Sites lists all available courses for a logged-in customer.

On a Membership Site with lots of available courses, the course list quickly gets long and cluttered. 

Also, i try to organize groups of courses in different places on my membership site, to keep things easy to navigate. Therefore, it does not always make sense to have every accessible course in a given course list.

Therefore i suggest adding a "Featured Courses" page section, similar to the "Featured Products" section, where it is possible to manually select a set of specific courses to be displayed (given that the logged-in user has access to them). 

<img width="254" alt="skaermbillede 2017-11-21 kl 15 27 07" src="https://user-images.githubusercontent.com/16045305/33077769-f47c4a20-ced0-11e7-9965-0d3b9983450b.png">

What do you think? does this sound useful?

**Comment by AndreaSchroeder77** [comment]
This would be very useful for me.

**Comment by CoachWouter** [comment]
Hi @calvincorreli and @nickbruun, thanks for the update. I’d love to find a way to jump to my courses quickly from the content menu. Am I overlooking anything? Thanks!

**Comment by calvincorreli** [comment]
Implemented now.
