### ISSUE TITLE
Having Most Recent User Contributions in Membership Sites

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#192]
Displaying the Most Recent User Contributions is a really helpful feature in Spaces - my members check it regularly to see what other members are talking about in different classes/pages across the space. 

I would like to move to a membership site but this is such an important feature for member usability and engagement.

**Comment by AndreaSchroeder77** [comment]
I just noticed that the most recent user contributions does show up in my dashboard for the membership site - is there a way to make it visible to my members? 

I have moved my space to the membership site and my members are assuming that if they leave comments in classes that other people will see them and join in the discussion, but I am the only one who can see that they commented.

**Comment by AndreaSchroeder77** [comment]
Now that I have been using the membership site for 2 weeks, I am getting more and more complaints from my members about this. They want to see what's happening on the site so they can participate - they're feeling like they are being blocked from being able to see what's happening.

Yes they can see new forum posts by going into the forum.

But I have a lot of little classes set up - and when people do a class and leave a comment, when others can see this new activity on the front page - then they join in the discussion. Then they re-engage with the class. 

Many have tried subscribing to everything but then get frustrated by all the emails they get. They don't want instant notifications, they want to see what has been happening on the site when they log in.

I don't understand why the latest comments are visible to ME in the site's dashboard instead of being visible to my customers. So I have been copying and pasting those each day into a forum thread so that people can stay somewhat updated.

The problem there is that those posts are displaying really strangely. For example, this is where is there today:

++++++
January 10, 2018 |  
-- | --
9:57am | Sharon Haines and one other replied to comment on Wednesday 10 January sharing in Masterminds
January 09, 2018 |  
10:02pm | Sharon Haines and one other replied to comment on January 7, 2018
10:01pm | Sharon Haines and 2 others replied to comment on January 7, 2018
10:00pm | Sharon Haines and one other replied to comment on January 7, 2018
10:00pm | Sharon Haines and 3 others replied to comment on January 7, 2018
9:59pm | Mary Stambaugh and 3 others replied to comment on January 7, 2018
9:32pm | Jenn George replied to comment on Tuesday 9 January sharing in Masterminds
9:11pm | Sharon Haines and 3 others commented on Tuesday 9 January sharing in Masterminds
8:58pm | Karen Fahy and one other replied to comment on Tuesday 9 January sharing in Masterminds
7:35pm | Clemencia Rosado replied to comment on Accountability January 7th in Celebration Feedback Encouragement + Advice

++++++

Out of 10 spots, FIVE are taken up by one thread - this leave five other discussions hidden from the members, which means those discussions just die because no one can see them and join in.

**Comment by tueolesen** [comment]
I can totally back this request up - Forums are an important part of keeping members engaged, and not everyone wants things to go (and get lost) in an external Facebook group. 

So a "yes please" from me too  on this one!

**Comment by Ryan-Henderson** [comment]
And a yes please from me as well.

**Comment by AndreaSchroeder77** [comment]
Ryan, this is available in membership sites now.
