### ISSUE TITLE
Option of limiting a 2-tiered affiliate system to 2 levels (i.e. restricting downstreams in signing up new affiliates)

### ISSUE THREAD

**Issue by Roulund** [Simplero/Roadmap#194]
We are going to have a number of Regional Partners around the world, whom we want to give the the option af signing up downstream affiliates. However, when we use the 2-tiered affiliate system, also the downstreams have to option to sign up new affiliates and thereby become upstreams. We want to be able to cut that possibilty off for the downstreams, so it is only our Regional Partners who can sign up downstream affiliates.  After discussing the issue in the Danish Office Hours today with Merete, I suggest that the easiest way to solve this is to have a check box next to where we choose the 2-tiered affiliate system, that allows us to limit the Program to to only 2 levels, so the downstreams cannot signup up their own affiliates.

![image](https://user-images.githubusercontent.com/32578786/33439356-87ce0246-d5ed-11e7-99f3-2ba64e38d75e.png)

**Comment by calvincorreli** [comment]
So you're saying any affiliate without an upstream can sign up downstreams, but if you're already a downstream, you cannot add additional downstreams?

**Comment by Roulund** [comment]
Yes, that is the option we will like to be able to choose. In that way we can make exclusivity in the privelege of makinging downstreams. This will be useful for our regional partners.
