### ISSUE TITLE
The ability to add content to forum categories in sites

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#196]
In my space, I could add content to the top of a category page in the forum, to explain what each category was about. This was important to help my users understand how to use the forum.

For example: I have a peer mastermind group in a forum. The text I added at the top of the page welcomed new members and explained how the mastermind worked so that they felt welcome to join in.

In sites, this is now impossible.

I have never seen a forum that didn't have descriptions for the different categories - I can't even figure out how to set up the site forum in a way that will invite new member engagement.

**Comment by calvincorreli** [comment]
Could this be solved with a sticky/pinned post in each category?

**Comment by AndreaSchroeder77** [comment]
That would be better than nothing for sure. It would still be preferable to be able to put content on the top of the page - like having a short video welcoming people and explaining the guidelines is much more welcoming for members. 

And sometimes I would want to change the content depending on what's happening in the group and people tend to ignore sticky posts after they've read them once.

**Comment by calvincorreli** [comment]
This will deploy tomorrow.
