### ISSUE TITLE
Course_id in HTML for styling

### ISSUE THREAD

**Issue by infospray** [Simplero/Roadmap#198]
Hi

I would like to add some kind of banner or styling per course (in the new membership sites).

Right now I cannot see that I can upload a banner or anything similar to what you could do in Spaces. 

Because of this, the new courses in the membership sites look awfully... well... white... 

Currently I can style the normal pages, but not the lesson pages. And since the members spend most of their time in the lesson pages, they are all very white. 

It would be great to be able to customize the overall feel of the modules and lessons even more. 

However since this might be a bigger operation, I thought you might implement something really simple. 

The course/module/lesson id somewhere in the HTML (either in class name or element ID) so I can target individual courses, modules and lessons in the CSS. 

This shouldn't take more than 5 minutes and won't influence other features or functionality.

Thanks :)

**Comment by calvincorreli** [comment]
This should be out later today.

**Comment by infospray** [comment]
Well it looks good.

I've found the course_id in the course overview page, but I cannot see the course_id in the lesson pages. 

See: https://www.evernote.com/l/ACA9bJ3FpI1IPoTkWzjpoRimnMW6bqX8V6w

I can only see a course_lesson_id. This would of course also be nice, but since the use case I'm after is a unique styling per course, I would of course prefer the course_id to also be in the lessons :)

**Comment by calvincorreli** [comment]
Try now.

**Comment by infospray** [comment]
It works... YEAH! Thanks.
