### ISSUE TITLE
Header as a layer on top of a big picture

### ISSUE THREAD

**Issue by moso1975** [Simplero/Roadmap#200]
I would like the header on the homepage to be a layer on top of a picture also covering the section below the header. See Simpleros own homepage for an example.
![fd719f04-de48-488d-8b0c-25bea5e55f9d](https://user-images.githubusercontent.com/34305004/33659656-4cc09d38-da81-11e7-9627-bf1c8245f2f7.jpeg)

Also I would like that the header stay fixed so you always see it when you scroll down the homepage.

Regards,
Morten

**Comment by calvincorreli** [comment]
Right near the top of our list is a theme editor, so you can change these things yourself. That should do the trick.

–Calvin
