### ISSUE TITLE
Disable Simplero users getting added automatically as contacts

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#201]
Right now, users who are logged into their Simplero accounts get automatically added as contacts. I would like an option to disable this so that my data stays clean, and that my contacts only show my actual sign-ups.

**Comment by calvincorreli** [comment]
Hi Stephen

I'm not understanding what you're saying here at all.

"users who are logged into their Simplero accounts" ... clearly, if I log into my Simplero account, I don't get added as a contact on your account.

What exactly are people doing to get added as contacts?

**Comment by stephenhutson** [comment]
Hi Calvin,

Sorry, I left out a key component here. They're getting added to our account as contacts if they _visit our website_ while logged into their Simplero account. Effectively, any Simplero user that has ever visited our site is automatically added as a contact.

**Comment by calvincorreli** [comment]
Thank you, this makes sense. Will put it on the shortlist.

**Comment by calvincorreli** [comment]
Implemented. Will be deployed shortly.
