### ISSUE TITLE
Set multiple conditions within automation settings

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#206]
Right now, in the settings of an automation, you can only choose one condition. I would like the ability to set multiple conditions. 

For example, send to contacts with "x" tag, but exclude contacts with "y" and "z" tags. 

I'd like that option in the individual automation steps settings as well as the overall automation settings. 

Thanks!

**Comment by calvincorreli** [comment]
It's coming. The single condition is to carry us over. Lets you do most things, and was super quick and easy to implement.
