### ISSUE TITLE
Add notes to automation steps

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#209]
I would like to add notes to steps in an automation. This is very helpful when someone else has to step in and decipher automation that they didn't create, or for simply keeping everything straight in my head. :)

Thanks

**Comment by calvincorreli** [comment]
Oh, that's a good idea. Hadn't thought of that.

**Comment by stephenhutson** [comment]
I've been really digging into the automations and triggers these last several days. I love some of the stuff I'm able to do. You've created a deceptively powerful software!

**Comment by kaslam311** [comment]
This is too funny! I was going to request the exact same thing only to find out Stephen already did :-)

I made a video about it. Might as well not let it go to waste!

https://www.useloom.com/share/4515808780d8473a8db16a9b08ae5bea

**Comment by calvincorreli** [comment]
And just today, in the steam room, I was thinking about this and other changes I want to make to automations...

**Comment by kaslam311** [comment]
Ha!! I think running a marketing automation suite is a lot like that book "If you give a mouse a cookie..." :-D The more people love your tool the more they're going to ask of it. Thanks Calvin! Let me know if I can help with anything here. I'm always happy to be a part of a brainstorming session.
