### ISSUE TITLE
Layout options for the countdown timer

### ISSUE THREAD

**Issue by Umahro** [Simplero/Roadmap#21]
The ability to set up a timer on landing product pages is awesome.

What would take it to the next level is more options:

1. The ability to control where it is placed on the landing page
2. The size and layout (color, fonts etc.).

**Comment by calvincorreli** [comment]
Good points, all. The size I'll get fixed, so it stays on one line.

The placement, I'm going to punt on. We're going to rewrite the landing pages completely so they use the same system as the new website builder.

Will let you know when the size change has been deployed.

–Calvin

**Comment by calvincorreli** [comment]
I've made the countdown timer smaller now.

https://nutrimenta.simplero.com/page/73561
