### ISSUE TITLE
"Add purchase" on contact page should have Internal product names in the list

### ISSUE THREAD

**Issue by themanagementcoach** [Simplero/Roadmap#212]
I have products with the same "catalogue" name but different internal name. The reason for this is currency - in order to not give customers an option of switching to a currency so that they get a beneficial exchange rate discount. This setup allows me to direct the exact currency that the client should receive. Same product, different currency. The way I know the difference is the "Internal product name".

When I go to add a product to a customer from the contact's page, I get a list of all the client-facing product names instead of my internal product names. I can't tell them apart.

It would be great of the "Add purchase" button on the contact page listed the Internal product names.

**Comment by calvincorreli** [comment]
Noted. Will put on the shortlist.

**Comment by calvincorreli** [comment]
Have implemented. Will deploy later today.
