### ISSUE TITLE
HTTPS for custom subdomains

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#218]
Per the Facebook group discussion, a few folks have expressed interest in having https for our custom domains. I know that the actual Simplero domain is secure, but now that browsers are starting to cause a fuss about https, it would be great if the custom domains were https too. 

Thanks!

**Comment by calvincorreli** [comment]
It's a power grab by google, plain and simple, but there's nothing we can do but comply. On the shortlist.

**Comment by stephenhutson** [comment]
Completely agree. It's frustrating that they're using scare tactics on the user's end. We've had a few folks say that they got an error warning when they came to the site. Very annoying.

**Comment by calvincorreli** [comment]
Done!
