### ISSUE TITLE
Categories in Email Library

### ISSUE THREAD

**Issue by sherrieanne** [Simplero/Roadmap#22]
As we begin to really use automations more and more, our email library is becoming very very full. It would be great if we could create categories in there so that we could find emails in the email library easier.

**Comment by ManjirS** [comment]
Yes Please. This would be great.

**Comment by SarahEKerr** [comment]
ditto!

**Comment by calvincorreli** [comment]
We're considering a global labeling system for the admin interface where you can label anything across the board - library emails, media files, contacts, products, affiliate programs, anything.

**Comment by Wombatgeorge** [comment]
Yes please... looking forward to this!
