### ISSUE TITLE
Anchor tag functionality for buttons on landing pages

### ISSUE THREAD

**Issue by CarlyBrownVA** [Simplero/Roadmap#220]
I was designing a landing page for a client this week and she wanted buttons throughout which, when clicked, took the user to the buying section of the page and gave this Gabby Bernstein landing page as an example: https://gabbybernstein.com/bookgift-fb/.

**Comment by calvincorreli** [comment]
can't you just add a button with link to # and the ID of a section on the page?

Use "Inspect" in your browser, and you should be able to get it done.

**Comment by CarlyBrownVA** [comment]
I'm not a developer so I didn't know this was  possible. I'll research it for future but it's longer than simply having the option on Simplero landing pages.
