### ISSUE TITLE
Problem with conversion with zero-decimal currencies

### ISSUE THREAD

**Issue by robmcneilly** [Simplero/Roadmap#227]
I want to include Japanese yen in my price options and this isn't available at this time.

Is there any way it can be included?

Thanks

Rob

**Comment by calvincorreli** [comment]
Here's the relevant info from Stripe:

https://stripe.com/docs/currencies#zero-decimal

**Comment by robmcneilly** [comment]
Thanks Calvin

The problem was within “prices”, when I added Japanese yen, eg looking for the equivalent for US$600, it was converted into 700 yen. When I multiplied this by 100, to 70,000 yen it converted it to US$60,000 so I had to delete it.

No huge problem, just a minor glitch.





Robert B McNeilly MBBS
CET
The Milton H Erickson Institute of Tasmania
191 Campbell Streets” 
Hobart TAS 7000
Australia
Mobile 0433 273 352
rob@cet.net.au <mailto:rob@cet.net.au> 
www.cet.net.au <http://www.cet.net.au/> 
sign up for my newsletter <https://robmcneilly.simplero.com/page/73185-cet-news>




On 3 Jan 2018, at 11:24 pm, Calvin Correli <notifications@github.com> wrote:

Here's the relevant info from Stripe:

https://stripe.com/docs/currencies#zero-decimal <https://stripe.com/docs/currencies#zero-decimal>

**Comment by calvincorreli** [comment]
Ok, sounds like I misunderstood something. I'll take a second look.

**Comment by calvincorreli** [comment]
It's fixed now.

**Comment by robmcneilly** [comment]
Perfect. Thanks Calvin.





Robert B McNeilly MBBS
CET
The Milton H Erickson Institute of Tasmania
191 Campbell Street
Hobart TAS 7000
Australia
Mobile 0433 273 352
rob@cet.net.au <mailto:rob@cet.net.au> 
www.cet.net.au <http://www.cet.net.au/> 
sign up for my newsletter <https://robmcneilly.simplero.com/page/73185-cet-news>




On 5 Jan 2018, at 5:23 am, Calvin Correli <notifications@github.com> wrote:

It's fixed now.
