### ISSUE TITLE
Set permissions for membership site pages

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#233]
We have several different levels of membership, with increasing levels of access to our content as you upgrade your membership. Right now, I have separate pages that are set fire a trigger to auto-publish the appropriate page when someone purchased the right membership. It's pretty tedious.

Instead, I would love to be able to define access to a page based on the product they've purchased, just like the Courses. So if a user tries to view the page but they don't have access to the content, they instead see a page that says "You don't have access to this" or something similar. 

Thanks!

**Comment by calvincorreli** [comment]
We'd rather make it so you can do what you want with courses, than add this to pages.

**Comment by stephenhutson** [comment]
I'm confused. I can already select access based on the product for courses. I'm asking for that same feature to be built out for pages within a membership site. So I can simply select who has access to the page instead of having to auto-publish the pages through automation.
