### ISSUE TITLE
Track UTM parameters in order forms

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#235]
I would like for Simplero to track UTM parameters when a user signs up for a list or purchases a product (mainly purchases a product). It would allow me to know for sure which source created the member. 

If there's something like this in place already then please let me know! If not, this would be a game changer for us.

**Comment by calvincorreli** [comment]
Hi Stephen, not a bad idea.

Tell me more, please.

What exactly would you want to grab?

What do you want to do it?

Are you talking about landing pages, or also embedded forms?

**Comment by stephenhutson** [comment]
I would want all of it! We use UTM parameters in our paid advertising and for our content marketing. A user visits one of our ads or reads our blog, and then decides to purchase one of our memberships. I want that order form to capture the UTM data. The order form is the most important for us.

I'm envisioning fields for the UTM parameters in the "Conversion info" section on the right side of the contact view. I'd want to see:
Source
Medium
Campaign
Content
Term

If there was nothing for that specific UTM parameter, the field could simply be blank.

This brings up another point though: I think 2 UTM sections would be ideal. One is the UTM data for their very first order form fill out. The first time they sign up, if there's UTM data, it saves and is locked. It can't be changed. 

Then there's another UTM section that always shows the latest UTM data for that contact. This allows me to see how someone initially came in to our ecosystem and then, if they upgraded to or purchased something else later, I can see that UTM data as well and compare the two. 

Did I explain that well? If I didn't, here's a video that might be better: 
https://www.useloom.com/share/9004d1e768824eceaecd766f5f303dbc

**Comment by calvincorreli** [comment]
Thanks, @stephenhutson. Super helpful.

So it looks like they have first, last, AND a set called UTM ___... what are the UTM ones exactly in that scenario?

Also, I'm guessing we'd have to store the UTM vars in the session the first time they hit our site, as they might be browsing around a bit before they actually opt in a purchase something, right?

Any limit on how long we should remember that stuff for? I'm guessing no limit, right? We'd want to capture that info as much as possible?

We can also store it in a cookie, which is longer-lived than the session.

Thoughts?

**Comment by stephenhutson** [comment]
Hi @calvincorreli , 

Those UTM fields are actually custom fields we created to link with our chat software. The existing fields weren't working and that was the solutions our developers came up. So for now that can probably just be ignored. 

For storing the UTM vars, that sounds exactly right.

I wish I knew what the best practice is here! My thought is no limit since they could come back 3 days later and take action. It would be nice if the information was still captured in that scenario.

I'll have to defer to you here to compare cookies vs sessions.  I'm afraid I don't have much knowledge about the difference.

Thanks!

**Comment by nicolabird** [comment]
Yes, we need this too!

**Comment by calvincorreli** [comment]
This has now been deployed.
