### ISSUE TITLE
Number of login sessions allowed

### ISSUE THREAD

**Issue by JesperChristophersen** [Simplero/Roadmap#236]
We´d appreciate the opportunity to restrict access to our membership site to only allow logins from two or three devices at the same time – to avoid members sharing their login with others.

**Comment by calvincorreli** [comment]
We're not fans of punishing paying customers by making life harder on them. Not likely to happen.

**Comment by JesperChristophersen** [comment]
Hi Calvin

I´d like to clarify:
We are of course not fans of “punishing paying customers” either – who would want that? I don´t feel punished by Netflix and HBO because they have a limit – I never notice it, so it´s not making my life harder. If anything, I benefit from it, because it let´s them ensure, that everyone enjoying their content also contribute; making them able to keep producing more and even better content.

We´ve had non-members asking us for support. They wanted our help, finding content on someone else´s membership, which tells us, that we have an issue with this, so I ask for a way to control it and to avoid several people sharing the same membership.

I´m not asking you to make a mandatory restriction for all Simplero users, - I´m just asking that you consider offering us the opportunity to switch a restriction on and off.

Some products are easier shared that others – I couldn´t share my Simplero account with my friends even if I wanted to (which I of course would never do), - so that will never be an issue for you I imagine, - but our membership product can easily be shared by large groups of people, sharing the same account and we would just like to avoid that – of course without punishing paying customers.

All the best
Jesper
