### ISSUE TITLE
Auto-renew OFF/ON - search feature

### ISSUE THREAD

**Issue by mortenspindler** [Simplero/Roadmap#238]
We have a very dire need to be able to see how many subscribers have se AUTO-RENEW to off on prodocts with monthly/yearly payments.
We asked the support if this was possible, but Merete Stenner told us, that it is not – and we can not download a CSV that shows us how many people have se their status to Auto-renew OFF.
It is crucial for us to be able to do this.
Why?
Because when hundreds of people sign up for a monthly payment of a certain amount, many will eventually cancel, and we NEED to be able to make statisticly accurate predictions about the number of members/income etc.

**Comment by DitteMA** [comment]
a direct notification when they set auto-renew off would be nice to - like when an installment fail.

**Comment by jonasnapier** [comment]
Totally agree - we need this.

**Comment by calvincorreli** [comment]
There's now an auto-renew column on the purchases table that you can include in your views and your downloads.

**Comment by mortenspindler** [comment]
Seriously?
"That's what makes you dat guy"
[citat: Bruce Willis i Die Hard 4]

**Comment by calvincorreli** [comment]
You seemed quite adamant about this, haha :)

Don't remember that scene, though I've probably seen it a handful of times ... youtube clip? ;)

**Comment by mortenspindler** [comment]
https://youtu.be/Qga3aLPB0YE

**Comment by mortenspindler** [comment]
And thanks for teaching me a new word too (Adamant).
