### ISSUE TITLE
Can we be able to update a member's profile for them.  & Member directory

### ISSUE THREAD

**Issue by MatenPet** [Simplero/Roadmap#240]
Most of our contacts are too busy to do it themselves or ask us for their login id & password... I would like to be able as an admin to update their member profile for them. 

Also in a perfect world - using the member profile's - I would like to be able to have them auto populate into a member directory (using custom fields that we decide - like first name, last name, company name, website, email, facebook & twitter, allow for photo and company logo) then trigger to ask for an admin to assign a category.  

For example: 

They buy a membership product which auto populates them into the member directory asking an admin to assign them a category.  

Once the category is set, then they show up in the member directory for the length of their membership... when their membership expires - they would automatically be removed from the directory and placed in past member status.  Still kept as a contact and on lists, but not allowed on the directory.

**Comment by calvincorreli** [comment]
I don't think this is something we're going to get to anytime soon.
