### ISSUE TITLE
Have "post a follow-up" link in emails link directly to that comment

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#241]
This is for blogs, classes and forums on the membership site.

When you are subscribed to something and get an email with a new comment the button says "post a follow-up" but that link takes you to the top of the screen.

When there's a conversation happening in the comments that makes it really hard to find the comment that you actually want to respond to.

I made a screen capture to show what is happening right now:
https://vimeo.com/251321278

**The password is Simplero**

As you can see, some of my members are wanting to stop participating on the site because it's just too frustrating.

**Comment by mylesboone** [comment]
This was fixed on 5/11/18.
