### ISSUE TITLE
Feature request: 1:1 email-support option in Simplero

### ISSUE THREAD

**Issue by DitteMA** [Simplero/Roadmap#242]
It would be nice with af 1:1 support option in simplero for my users. Best with a subscription option, that still leaves acces to the Q&A's after the subscription expires. 

Also all the data should belong to me, and follow the General Data Protection Regulation

best Ditte

**Comment by calvincorreli** [comment]
Hi Ditte

I have no idea what this means.

Can you explain in a bit more detail?

–Calvin

**Comment by DitteMA** [comment]
Hej Jeg svarer lige på dansk.

Jeg har brug for at kunne give 1-1 skriftlig coaching i forbindelse med
salg af kurser. Pt giver jeg emailsparring supplerende til onlineforløbet
via gmail, men det betyder at jeg skal holde øje med når deres emailsparing
udløber eller forlænges + at jeg får problemer i forhold til de nye
dataregler. Så det ville være meget lettere for mig at administrere, hvis
det kunne ordnes inde i simplero.

vh Ditte

2018-01-18 18:53 GMT+01:00 Calvin Correli <notifications@github.com>:

**Comment by calvincorreli** [comment]
Can we have it in English, please, so other team members and other customers can understand, too?

Thank you very much!

–Calvin

**Comment by DitteMA** [comment]
Ok. I would like to be able to give written  1:1 support to my customers
inside the online course. At the moment I use gmail for the email support
part, but it means that I have to manually keep an eye on when their email-
coaching is up or renewed. It would be a lot more smooth if it could all be
inside Simplero- and also more in line with new European datar egulations.

best Ditte


Den 18. jan. 2018 kl. 18.59 skrev Calvin Correli <notifications@github.com>:

Can we have it in English, please, so other team members and other
customers can understand, too?

Thank you very much!

–Calvin

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Simplero/Roadmap/issues/242#issuecomment-358729695>,
or mute
the thread

**Comment by calvincorreli** [comment]
We have this on our roadmap.

**Comment by DitteMA** [comment]
Sounds great, do you know when it will be up and running?

**Comment by calvincorreli** [comment]
No idea, could be a while.
