### ISSUE TITLE
MobilePay integration

### ISSUE THREAD

**Issue by hasherdk** [Simplero/Roadmap#243]
It would be great with a proper integration to the Danish payment provider MobilePay. It's getting quite big in Denmark, and the old school manual integration in Calvin's video from back in 2014 or so doesn't really do it justice anymore. It has been possible to integrate directly in web shops for quite some time now.

I know that it can be done through QuickPay/Clearhaus/Teller etc., so it may require minor changes on your end (I don't know the details, so no guarantees). Otherwise, please see here for more information: http://mobilepay.dk/da-dk/erhverv/Pages/mobilepay-online.aspx (in Danish)

Thanks in advance for considering this! :-)

**Comment by JannieLearning** [comment]
I agree, that MobilePay integration  would be great

**Comment by calvincorreli** [comment]
It's on our roadmap.
