### ISSUE TITLE
Change button color in List sign-up form

### ISSUE THREAD

**Issue by Annebente** [Simplero/Roadmap#245]
On sites and landingpages we can change the button color. But when I use the List it uses the accent-color from Settings/Colors & Grapics. I would really love to be able to change the button color for list opt-in.

Hope this is possible

![image](https://user-images.githubusercontent.com/32258272/35154562-f4fc8f22-fd2a-11e7-9553-71f64540d4cc.png)

Anne Bente, Inspiro Academy

**Comment by calvincorreli** [comment]
I think we got that done now.
