### ISSUE TITLE
URL tag's not working unless clicked from mail

### ISSUE THREAD

**Issue by JannieLearning** [Simplero/Roadmap#246]
I tried to test the URL tags both for external URLs and for URLs on Simplero, but if members open these pages from i.e. an activity in an iframe, then that member does not get the tag. It would be great to be able to track exactly who looked at a specific page, that they gained access to through some specific content in the end of a training session.

**Comment by calvincorreli** [comment]
I don't understand what this means. "if members open these pages from i.e. an activity in an iframe" ... can you try to explain more clearly?

**Comment by JannieLearning** [comment]
The key is, that I am trying to track who completed and passed some training. The training will play either as Iframe og just as embedded HTML. If people pass, I can put a buttom for them to click. This could take them to a new page that says 'congratulation'. I would like to track, who saw this page.

**Comment by calvincorreli** [comment]
And what's the training, and why would an iframe be involved?

**Comment by JannieLearning** [comment]
It is not just video training, but classic e-learning with exercises, animations etc.

/Jannie

 

 

Fra: Calvin Correli [mailto:notifications@github.com] 
Sendt: 19. januar 2018 15:26
Til: Simplero/Roadmap <Roadmap@noreply.github.com>
Cc: JannieLearning <jannie@digitallearning.dk>; Author <author@noreply.github.com>
Emne: Re: [Simplero/Roadmap] URL tag's not working unless clicked from mail (#246)

 

And what's the training, and why would an iframe be involved?

**Comment by calvincorreli** [comment]
What are "URL tags"?
