### ISSUE TITLE
In membership sites: possibility to mark completed lessons as not completed

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#247]
In spaces you an mark lessons as not completed after marking them as completed. In membership sites you cannot at the moment. Some of my students like to go through my courses more than one time, so my guess is they will appreciate this possibility when retaking the course - also I think some might mark a lesson as completed by accident, so it would be good to have the opportunity to correct that

**Comment by calvincorreli** [comment]
Makes sense.

**Comment by ingjerd123** [comment]
Is this implemented yet? I don't think so, but there is a trigger that uses "mark as uncompleted", and that cant be used until you can actually do it ... its been 1,5 years now, so I'm not sure if there is any point in making requests at all. Please let us know if its a waste of time

<img width="869" alt="Skjermbilde 2019-10-17 kl  14 40 38" src="https://user-images.githubusercontent.com/26975740/67009846-cb950580-f0ec-11e9-86c9-1e766cf75572.png">

**Comment by midnightmonster** [comment]
I know it's been a long time coming, but we did finally make this possible a couple weeks ago.
