### ISSUE TITLE
Folders to organise products/automations/lists etc

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#252]
I have pages of automations and although the starring system is somewhat helpful to keep those you need in view, I have for example, 7 automations all do to with one particular funnel - if I want to work on those I have to keep scrolling through the pages each time I save out of one.

I have collections of products, lists, automations, tags etc and would be great to be able to organise them in folders/categories etc. 

Thanks!

**Comment by calvincorreli** [comment]
We have that on our internal priority list.

In the meantime, you can add some codes to the internal names, and set up tabs on your automations screen based on a search for those codes: Type the code into the big search field, and then click to save the view.

**Comment by nicolabird** [comment]
Oooh I'll give that a go, but probably will wait for folders if they're on
their way! Thanks Calvin x

Love,

Nicola

PS. Want more peace of mind? Join the Little Peace Of Mind Seven Day
Program. <http://alittlepeaceofmind.co.uk/7-days/>

The content of this email (and any attachment) is strictly private and
confidential. If you are not the intended recipient of this email then
please inform the sender and delete it from your mail box or any other
storage mechanism.

Please note that this email has been created in the knowledge that internet
email is not a 100% secure communications medium. A Little Peace of Mind
advises that you understand and observe this lack of security when
emailing. Although A Little Peace of Mind has taken steps to ensure that
this email and any attachments are free from viruses, A Little Peace
of Mind advises
that in keeping with good computing practice the recipient should ensure
that this email is actually virus free.


A Little Peace of Mind is a trading name of The Simplicity Project Limited,
a company incorporated in England and Wales under registered company number
08834451 and whose registered office is located at Rose Farm, Windlesham
Road, Chobham, GU24 8SY

**Comment by calvincorreli** [comment]
You're welcome to wait, but we're not making any promises about when. I'd play with the other thing if I were you. It's a neat trick to learn anyway.

**Comment by nicolabird** [comment]
Ok will do!
