### ISSUE TITLE
Upsell - two prices are displayed 

### ISSUE THREAD

**Issue by ManjirS** [Simplero/Roadmap#258]
![image github upsell price](https://user-images.githubusercontent.com/28048176/35574132-dedec4ae-05d0-11e8-85d1-775fe743e0a5.png)
Just a potentially minor issue. I had a chat with Deanna who told me to add it here. 
When the upsell page displays, at the bottom it shows the regular list price for the original product and the upsell price. 
It looks like the person is paying both amounts and may be disconcerting. 
Deanna says there isn't a way to remove this and it should be added here. 
[](https://eu.simplerousercontent.net/uploads/simple_attachment/file/93671/Screen_Shot_2018-01-03_at_02.43.05.png)
So I hope you can see this link or the image and the two prices $190 and $40 when I only want it to show $40 at this point. 
Thank you.

**Comment by calvincorreli** [comment]
Fix being deployed now.
