### ISSUE TITLE
Hiding "Dine Spaces..." Link

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#260]
In membership sites, there is a "Dine Spaces..." link at the top of menus.

Currently it cannot be hidden, and as users can still access their space content via the "avatar icon" link in the menu, and then going to "Mine ting og Sager" -  https://simplero.com/purchases - the space content is still accessible.

I think it is cluttering the menu a bit, and i suggest one of two approaches:

1) Option in Membership Site settings to "Hide link to spaces in menu"

or 

2) Include "Available Spaces" as a Page Type, allowing it to be added to the Pages list of the membership site. Then inside the Page Settings for that link, the ordinary option allowing it to be Hidden just like other pages can be hidden from the main menu.
<img width="338" alt="skaermbillede 2018-02-02 kl 10 43 56" src="https://user-images.githubusercontent.com/16045305/35726683-ff75b3da-0805-11e8-9847-0c1dc7c8e054.png">

This would allow us to de-clutter the membership site layout even more, keeping things clean!

**Comment by tueolesen** [comment]
Could a simple approach be to give the link a CSS ID so we can hide it via CSS styling (display: none;) ?

**Comment by calvincorreli** [comment]
Rolling out now. It's a class, ``site-header__nav__item--your-sites``

**Comment by tueolesen** [comment]
Thanks! 

Works with the following CSS:

.site-header__nav__item--your-sites {
  display: none !important;
}
