### ISSUE TITLE
Simplero view broadcasts by list

### ISSUE THREAD

**Issue by donnaashton1** [Simplero/Roadmap#262]
I would love to be able to view sent broadcasts by LIST. I have several larger lists and it is hard to wade through all the emails to find the ones I want to duplicate or whatever for repeat campaigns.

**Comment by calvincorreli** [comment]
You can already do this.

Just click on the numbers under Broadcasts:

![screenshot](http://cloud.smpl.ro/472q2i25132e/[e8adfaa3233924c4bdb44ac645b6c6db]_Screen%20Shot%202018-02-06%20at%208.08.44%20PM.png)
