### ISSUE TITLE
Avoid redundant conversion pixel maintenance

### ISSUE THREAD

**Issue by christophcemper** [Simplero/Roadmap#264]
Hi

I find myself updating tons of *almost* redundant conversion pixel codes

on https://lrt.co/academy
we have one and the same conversion trackingpixel code for
multiple systems in EVERY  of the 30+ products

The only difference is a "product_code" -something like "ebook_link_audit",
and even in 3-5 places per pixel code

That makes updating the conversion pixel a tedious, error-prone work
and it would be amazing if Simplero would support a sort of
"Global Conversion Pixel Template" where we could place the template
and only have product_name_internal or something like that filled it

Please let me know if you have ​further questions and I'​d be happy to help​. 

Have a great day from sunny Vienna,
Christoph

**Comment by calvincorreli** [comment]
Done now. You'll find it under Settings > Product.

**Comment by christophcemper** [comment]
Amazing stuff Calvin - can't wait to implement this!

**Comment by christophcemper** [comment]
@calvincorreli what would be awesome is to also get the Product Category and Product Category-URL'ized so we can use that category e.g. for GA eCommerce or for different FB custom audience segments

**Comment by christophcemper** [comment]
Oh and the used coupon code could be an important addition for some, GA enhance ecommerce uses it always in examples

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#measuring-transactions

**Comment by calvincorreli** [comment]
Doesn't look like the version we use support it, but I've added coupon_code to the personalizations you can use in your own code:

https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce
