### ISSUE TITLE
give option to 'include or hide module/lesson from course overview'

### ISSUE THREAD

**Issue by nicolabird** [Simplero/Roadmap#265]
Love the new preview functionality :)

However I, like many I would imagine, include Q&A calls that you get access to if you're in the program when the call is held. So the course overview on the 30 Day program would look as if you're going to get all these additional Q&A calls if you join, which you won't. But I do want to be able to show some of the modules in the course overview (I think this is a great teaser functionality but misleading currently in my case so unuseable). 

So what we would need would be as well as being able to tick 'preview lesson' which we can do within each module now, also to have the option 'include/ remove from course overview'. 

https://www.dropbox.com/s/sedoij7rx3pu1ft/Screenshot%202018-02-04%2009.16.00.png?dl=0

**Comment by calvincorreli** [comment]
I'll deploy this tomorrow.

**Comment by nicolabird** [comment]
Thank you!

**Comment by calvincorreli** [comment]
Done now

**Comment by nicolabird** [comment]
Thank you!

**Comment by nicolabird** [comment]
Thanks Calvin - as soon as I actually have the capability to actually
select my courses for preview I'll be using this! Unfortunately my simplero
seems to be missing that functionality at the moment on all but one of my
courses! Support ticket in so I know you're working on it...

Love,

Nicola

PS. Want more peace of mind? Join the Little Peace Of Mind Seven Day
Program. <http://alittlepeaceofmind.co.uk/7-days/>

The content of this email (and any attachment) is strictly private and
confidential. If you are not the intended recipient of this email then
please inform the sender and delete it from your mail box or any other
storage mechanism.

Please note that this email has been created in the knowledge that internet
email is not a 100% secure communications medium. A Little Peace of Mind
advises that you understand and observe this lack of security when
emailing. Although A Little Peace of Mind has taken steps to ensure that
this email and any attachments are free from viruses, A Little Peace
of Mind advises
that in keeping with good computing practice the recipient should ensure
that this email is actually virus free.


A Little Peace of Mind is a trading name of The Simplicity Project Limited,
a company incorporated in England and Wales under registered company number
08834451 and whose registered office is located at Rose Farm, Windlesham
Road, Chobham, GU24 8SY
