### ISSUE TITLE
Have Most Recent Posts include each forum post only once

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#268]
When I am teaching a class in my membership site, this is what the "most recent posts" starts to look like:

![recentposts](https://user-images.githubusercontent.com/26936818/35863551-aca22ab4-0b14-11e8-9641-510f714cee76.jpg)

There are only 15 spaces and 9 are taken up by one post.

This means 8 other threads are lost and those discussions just die because people can't see that they're happening.

I understand that you give a new line to each new comment, but think of what this looks like to the end user.  

How are they supposed so know which comment is which? How do they know which one they want to click on? There is NOTHING to give them a clue about that, just 9 different links to pick from.

They don't need to see each one separate like that since there is no way of knowing which comment is the one they'd like to look at anyway. So all they need is to see that there is a discussion happening in a specific thread, with a link to that thread.

The way it is now, with links going to specific comments, that can actually cause them to miss parts of the conversation because the end user does not understand that comments and replies to comments are two different things.  And there is no way for them to know which comment thread they are clicking on.

The ability to have the link go right to that specific comment would be AMAZING in the emails you get when you are subscribed to something!!!! So when you click "post a follow up" that link goes right to the comment you just read, because in that case you DO know which comment you want to respond to.

**Comment by AndreaSchroeder77** [comment]
A little while later now there are only 3 different threads showing on the front page and this class is just getting going.

![updaterecentposts](https://user-images.githubusercontent.com/26936818/35865869-3c4f2ddc-0b1b-11e8-88d7-7a40ba98838d.jpg)

**Comment by calvincorreli** [comment]
This has now been deployed.
