### ISSUE TITLE
Fixed "Burger" menu on mobile (like Simpleros own site).

### ISSUE THREAD

**Issue by mortenspindler** [Simplero/Roadmap#275]
On your own website (simplero-dot-com), the "burger" menu icon and logo stays at the top when scrolling on mobile devices (screenshot enclosed). 
I had the impression, that Simpleros own website was in fact created in Simplero, but the menu does not work that way when I create a site or a membership site.
However...
Being able to "freeze" the logo+burger-menu would be a huge step up for usability, as the menu is no good (and the reader might get lost), when the menu is hid in some far-off-scrolled-away top of the page that a reader might currently be at...
Also it is better to keep the branding (which is located next to the "burger" menu icon) at top of the site at all times, but for me, the menu
![img_1447](https://user-images.githubusercontent.com/28627953/36339560-0703c21c-13c9-11e8-86ea-4c64388133ba.png)

**Comment by tueolesen** [comment]
+1 vote from me on this one.

Also, the desktop-sized menu on simplero.com has elegant features like going from transparent to white on scroll...would be sweet to add that to membership sites too  👍

**Comment by jonasnapier** [comment]
We need this of course...

**Comment by Ryan-Henderson** [comment]
Yes please!

**Comment by calvincorreli** [comment]
This is done now. And the new simplero.com is in fact a Simplero site.
