### ISSUE TITLE
Membership Site: Be able to toggle/preview both as Logged In + Logged Out User

### ISSUE THREAD

**Issue by desireeeast** [Simplero/Roadmap#276]
Hi Simplero Team,

I'd love to be able to preview my membership site/courses as a logged out user without having to log out each time. Is there a way to toggle back and forth to preview what we're designing...this would prevent me from having to change customize settings and logging in and out to see what things look like as a student/customer who is logged out.

Here's a screenshot of an example:
http://www.evernote.com/shard/s238/sh/f646636d-f858-4ea2-92f1-687c21cc839f/84c4c8efd5826030237eb38bb198436b

Thanks so much :)
Desiree

**Comment by calvincorreli** [comment]
Ah yes. That's easy. Just open a "Private" or "Incognito" browser window, and copy-paste the URL from the page you're on into the new window, and bam! there you go!
