### ISSUE TITLE
Option to set 'noindex' on specific Membership Site pages to hide them search engines

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#279]
Membership sites have a sitemap /index.xml containing all published pages for that membership site.

Some of the pages i've added are confirmation pages for product purcases, list sign ups etc., so when customers complete a transaction they are sent to one of these pages.

These pages are not relevant for search engines so it would be neat to have an option to set 'noindex' for them, and hide them from the sitemap.xml to stop search engines from discovering the pages.

It can be done really simple, via adding a <meta> tag in the header:
<meta name="robots" content="noindex">

Thanks,
Tue

**Comment by calvincorreli** [comment]
I've added noindex to pages that are hidden from navigation, and I've taken those pages out of the sitemap as well.

That should do it, right?

**Comment by tueolesen** [comment]
Yep that does the trick. Cool!
