### ISSUE TITLE
Worksheet confirmation

### ISSUE THREAD

**Issue by sherrieanne** [Simplero/Roadmap#28]
It would be great if after you hit submit on the worksheet it gave some kind of response to let them know that it was saved. It is very confusing often times people hit submit more then once.

**Comment by calvincorreli** [comment]
You should see a confirmation like this:

![Confirmation](https://d3vv6lp55qjaqc.cloudfront.net/items/2c3U1k3Y13233R2d1G3t/Screen%20Shot%202017-04-20%20at%2010.37.14%20AM.png)

You don't?

**Comment by sherrieanne** [comment]
I'll go test it but I don't remember ever seen that. and the participant that pointed it out to me today was Robin Green who was filling out a worksheet for Lindsay. so maybe we need to make it prominent somehow. 

I'll go test now and report back

**Comment by sherrieanne** [comment]
ok yes I see it up at the top of the worksheet. But if the worksheet doesn't fit on the screen it doesn't automatically scroll to the top when it refreshes and so you would miss that unless you are looking for it. Maybe it would be better if it was a pop up screen, or at least when it refreshed it went to the top of the page.

**Comment by calvincorreli** [comment]
Gotcha, I'll change it so it shows up on the page, no matter where you've scrolled to.
