### ISSUE TITLE
Affiliate Leaderboard option to hide leads and revenue

### ISSUE THREAD

**Issue by ShivanSarna** [Simplero/Roadmap#281]
Affiliate leaderboard option to hide number of clicks, sales, or earns so that affiliates are not seeing what others have accrued. 

We would like to hide so and only show a ranking of affiliates with the most leads and revenue (two separate ranking options). 

Individual affiliates and internally we want to see the number of opt-ins and sales but we don’t want that visible to the outside.

**Comment by calvincorreli** [comment]
This is now implemented:

![Screenshot](http://cloud.smpl.ro/0A1e26223K1h/Screen%20Shot%202018-02-22%20at%2010.42.24%20AM.png)

**Comment by calvincorreli** [comment]
And thanks for the suggestion
