### ISSUE TITLE
Upsell price in same currency as product

### ISSUE THREAD

**Issue by andersronnau** [Simplero/Roadmap#287]
I just tested the buying process with a free price on the product Reclaiming Hope, which gave me an upsell in USD. 

So I changed the free price to be in both USD and DKK and picked DKK as the currency, but the upsell is still delivered in USD, which is not so cool since I am giving the same price in DKK incl. VAT as in USD ex. VAT. Which means that the Danes will experience a price that is 25% higher than promised...

Attached is screen dump from the upsell page when order form is in DKK and country is Denmark.

<img width="433" alt="skaermbillede 2018-03-22 kl 10 49 54" src="https://user-images.githubusercontent.com/26906975/37765097-a2c37e7c-2dc3-11e8-8d90-97dd864ff11b.png">

**Comment by calvincorreli** [comment]
That makes sense. We should totally get that fixed.
