### ISSUE TITLE
Label sections on themed pages

### ISSUE THREAD

**Issue by MatenPet** [Simplero/Roadmap#288]
When building a membership site, I have a home page and sub pages under that.   In building the sub pages I can name them apples, bananas, carrots etc.  but under the sub pages when I add a text&media section, I would love to be able to name the sections so I can easily find the ones I want in edit mode..
![feature-request](https://user-images.githubusercontent.com/28815915/37814507-9e778e62-2e27-11e8-8f42-c42321dc0f36.png)

**Comment by nicolabird** [comment]
Me too - I have one page with a huge number of these and impossible to find the one you want easily.

**Comment by calvincorreli** [comment]
This will be deployed tomorrow.
