### ISSUE TITLE
In pages: possibility to rename/label the sections

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#292]
Hi,

Sometimes I make pages with a lot of content and many sections. For example this page has 46 sections in total, many of them with the exact same name: 12 sections named "text and media", 11 sections named "text", 16 sections named "media" ...

https://norskgrammatikk.simplero.com/pages/supergod

This makes it quite hard to know what is what on the page and to rearrange the order of the sections without doing any mistakes. I wish for the possibility to name/label the sections with names of my own choosing, to make it easier to identify what is what.

**Comment by calvincorreli** [comment]
Duplicate of #288

**Comment by calvincorreli** [comment]
This will be deployed tomorrow.
