### ISSUE TITLE
Need a way to style link color in emails. CSS is overwritten with hardcoded style

### ISSUE THREAD

**Issue by christophcemper** [Simplero/Roadmap#295]
Been doing nice css styling in my email templates, 
but as long as you hardcode/hardstyle the font color, 
it's pointless to use an own template.

Why design an own template if Simplero
overrides the links to the "Simplero green" with

style="color: #5bc1a7 !important

I might be missing something,
but that renders the "custom email template" useless.

renders the work my designer put into styling one useless

please get this fixed, and I suggest by 

just adding an option to "colors"  to decide if hardcoded color yes/no and WHICH

Very aware that many email clients ignore the CSS,
so hardcoding might still be required for a while
but let us change the style/color please

thanks so much 
Christoph

**Comment by calvincorreli** [comment]
Can you try changing the link color under Settings > Colors and Graphics. I'm pretty sure we set the link color to what you specify there, not to the same color for everyone.

**Comment by christophcemper** [comment]
I tried. it says #4285f4
but the HC link color is as per example above

color: #5bc1a7 !important

**Comment by calvincorreli** [comment]
Have you reached out to support about this?

If not, please submit a ticket with the details, and you can reference this conversation with me, and we can take a look.

Can't see anything in the code that hard codes links to this specific color.

There's a link color setting on the email template as well, though, but that's only used for system templates, as far as I can tell.

**Comment by christophcemper** [comment]
I did request support first - was sent here :)
