### ISSUE TITLE
Internal name for products

### ISSUE THREAD

**Issue by carstenthybo** [Simplero/Roadmap#30]
Like for lists, it would be great to have an internal, non-public, name for products.

We have several products with the same name, but intended for different target groups. Some times you have to open the product to make sure that you are working in the right one.

**Comment by infospray** [comment]
Don't we already have this?

https://www.evernote.com/l/ACDpBGZWPRZGIZBoWP9bHLVLre_nhnLmFVs

**Comment by calvincorreli** [comment]
You're right, we implemented this, forgot to close.
