### ISSUE TITLE
When a product is closed remove from the Affiliate center as an affiliate link

### ISSUE THREAD

**Issue by ShivanSarna** [Simplero/Roadmap#304]
We found that when a product is closed or the sale ends the product is still listed in the Affiliate center as an affiliate link. We would like to only show our affiliates the list of products that are available for promotion so that they are less likely to grab the wrong or expired affiliate links. 

Why would affiliates need to still see past products as affiliate links? 
If needed then could we have a check box to specifically remove the closed or expired products from the affiliate link list?

**Comment by calvincorreli** [comment]
Will get this deployed this week.

**Comment by ShivanSarna** [comment]
Thank you! 

Shivan S Sarna
