### ISSUE TITLE
Captcha option for signup forms

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#307]
We've been getting spammed on one of our sign up forms and we have no way to fight it. I'd like to be able to add a captcha to any signup form to prevent this from happening in the future.

Thanks!

**Comment by calvincorreli** [comment]
I'd rather get better at fighting the spam subscriptions. I'll deploy a change later today or tomorrow.

**Comment by PlanetThoughts** [comment]
Greetings. I see Calvin commented, but what change was implemented? I am also receiving spam. I know a double-optin is one possibility to avoid fake subscriptions, but is there a chance that Simplero will implement direct support of CAPTCHA (e.g. reCAPTCHA) in Simplero forms?

**Comment by calvincorreli** [comment]
We do have CAPTCHA on suspicious signups, but we may need to update our heuristics. Can you let support know where the spam is coming in, and we can take a look?
