### ISSUE TITLE
Better mobilepay support

### ISSUE THREAD

**Issue by petervejrumterp** [Simplero/Roadmap#326]
At the moment you kind of support MobilePay - but not fully.

It could be wonderful if you had a fully integrated payment from MobilePay. It is possible to do, I have seen different products doing it. Example on great use of Mobile Pay is https://www.midttrafik.dk/billetter-og-priser/midttrafik-app/ 

I am sure that for your many danish customers, this would be a very popular feature.

**Comment by gitteasmann** [comment]
I must say it is a must as well. People have their phone next to them all the time, so it is much easier to buy for them. 
Please look into it right now :-)

**Comment by stillevandringer** [comment]
MobilPay is a must to fix - I ask why they don`t pay with mobilePay - and this is the answer:I dont bother to write all the numbers down. I lose almost 10 kr. everytime they pay with card - it is not okay that you haven`t done anything about this a long time ago - please make it easy to use mobilePay!!!

**Comment by GrafiskGuru** [comment]
MobilePay is The New cash for small payments. Stupid to leave that option out.

**Comment by stillevandringer** [comment]
I know - but as it funktion now - I lose people - to many numbers….

**Comment by Tanjarg** [comment]
I too vote for mobile pay! Surveys in DK shows that online shops loose business by not having mobile pay. It is THE payment method in DK.

Please fix this for all Danish users. Your competitor here in DK, Easy Me, has mobile pay integrated and are gaining customers cause of it. Just saying.

**Comment by stillevandringer** [comment]
Please fix it now!!!!

Sendt fra min iPhone

**Comment by superfitmor** [comment]
Having a more seamless solution with Simplero and Mobilepay would be extremely helpful for me too. Fixing it would be much appreciated. Thanks.

**Comment by Forfatter** [comment]
We need Mobilpay so much! We are loosing customers. Thanks

**Comment by Forfatter** [comment]
Oh, I will LOVE that!!! THANK YOU!!!!


----- Original meddelelse -----

**Comment by Pernillebrettonmeyer** [comment]
Oh, yes please pretty please.... 
I have just joined Simplero and I was beginning to regret that I did not stay at easyme...  the mobile pay is a must in Denmark and I need the sales :-)  
I would be so very, very happy - and would love to be happy that I chose Simplero :-)

**Comment by mylesboone** [comment]
We plan to release a beta feature tomorrow (probably late afternoon CET) with MobilePay via QuickPay. We'll need some people to put it through the ringer to iron out all details. Who's in?!

**Comment by mylesboone** [comment]
MobilePay integration with QuickPay is deployed.

**Comment by Pernillebrettonmeyer** [comment]
Wow  That is good news. Thank you so much :-) :-) 
Do you not need people for testing then?  
I do not have quickly yet but are working on it :-)  and would be glad to test it when I can...   but it seems that it is not nessecary?  
Again:  wow...   love it :-)

**Comment by mylesboone** [comment]
The MobilePay option is currently 'beta', so we'd gladly welcome you to use it and let us know if there's anything out of the ordinary.

**Comment by tueolesen** [comment]
Tested it
With a one-time payment for a product, seems to work good.

For a purchase with multiple installments, and for subscription prices, mobilepay is removed from the payment processor window.

Will Mobilepay support these kinds of prices, or is it only intended for one-time payments? (I don't know enough about the mobilepay service myself to conclude if it is technically possible to do installments / subscriptions via mobilepay).

Anyhow - Seems to be working for one-time payments at least :-)

**Comment by mylesboone** [comment]
@tueolesen Thanks for checking it out! 
Yes -- the single payment is a known limitation. I reached out to QuickPay about that and they've said that they are working to implement subscription capabilities.
