### ISSUE TITLE
Ability to edit/delete note in contact record

### ISSUE THREAD

**Issue by Ryan-Henderson** [Simplero/Roadmap#330]
Is it possible to create the ability to edit a note in the contact record note window, or delete a note that is no longer relevant?

I am finding a lot of typos in the notes section, and would like to edit them so that they are easier to read. Also, it would be helpful to be able to edit a note to add additional related notes in the same section. 

If not, the ability to delete a note would be helpful - at least that way I could copy the old message and repost a new corrected one.

Thanks.

**Comment by Ryan-Henderson** [comment]
It looks like this is a request that you have completed. Thanks so much!

**Comment by calvincorreli** [comment]
You're right.
