### ISSUE TITLE
Mobilepay

### ISSUE THREAD

**Issue by superfitmor** [Simplero/Roadmap#332]
Hi,

Can you please advise me on how you roadmap looks regarding a smoother implementation af Mobilepay?

To manually approve every sell that goes through Mobilepay is time consuming and potentially an annoying wait for my costumers.

Also I am sure it costs me many potential customers (as I can see in the "Purchases waiting for manual payment"-section where many never go hands and finish the buy) that the payment processor is not capable of sending a request through Mobilepay.

And perhaps more importantly I'm afraid that some might think of it as "dodgy" that the buying process isn't seamless as people are used to with Mobilepay – and this might reflect negatively on my business.

Best, 
Thora
Superfit Mor

**Comment by mylesboone** [comment]
Hi Thora,
We'll be deploying a beta MobilePay integration through QuickPay tomorrow PM sometime. We'd love to have you try it out to make sure everything flows smoothly. I'm going to close this issue, and you can follow here: https://github.com/Simplero/Roadmap/issues/326
