### ISSUE TITLE
Alphabetical listing of Membership sites

### ISSUE THREAD

**Issue by sherrybowers** [Simplero/Roadmap#338]
I would love to have my membership sites listed alphabetically in the membership sites screen or have the option to sort them alphabetically. I am creating private portal sites for my private clients, as well as, traditional course membership sites. I have a naming convention to list all my private client's portal sites together if they could be listed alphabetically.  
I love Simplero! Thanks! Sherry

**Comment by calvincorreli** [comment]
Implemented now. Will deploy later.

**Comment by sherrybowers** [comment]
Thank you! I am so excited about this.
