### ISSUE TITLE
Allowing two columns in landing pages

### ISSUE THREAD

**Issue by janejacksoncareers** [Simplero/Roadmap#344]
Hi - I've been creating landing pages and currently am only able to have a single column when I add text.  Can you create a feature that allows for 2 columns in addition to 1 column?  

For example I'd like to have information on the left and the option to add separate testimonials on the right on my landing page rather than have people scroll all the way down the page to find things.  

At the moment the only work around I can do is to have 'text & media' and create an image with my testimonials in the image to upload in the media section so it looks like 2 columns. You can see what I've done here as a work-around: https://www.thecareersacademy.online/page/87317 

Many thanks!

Jane

**Comment by nichart** [comment]
Hi Jane

I've used the FAQ-section before for this, the FAQ section creates 2 columns. 

Kind regards
Nick

**Comment by calvincorreli** [comment]
We also now have a "Text in 2 columns" section.
