### ISSUE TITLE
Membership sites » Sitename » Access » please consider using Internal name

### ISSUE THREAD

**Issue by nichart** [Simplero/Roadmap#346]
If you view: Membership sites » _Sitename_ » Access - it display the _product name_, not the _internal name_. We have several products with the same product name, but different internal names. This overwiev would work better with internal name or both.

![access___for_ldresparring_s_simplero](https://user-images.githubusercontent.com/4003363/43475354-c46c10b8-94f5-11e8-8d10-883cc697d284.png)

**Comment by calvincorreli** [comment]
Done!
