### ISSUE TITLE
Customizable button color

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#35]
I wish I could chose the button color on the website (Simplero Site). Right now you can only have one button color

**Comment by CarlyBrownVA** [comment]
I'd love this feature too! 

I was trying to design a sales page for a client this week and she had originally wanted 2 different button colours on the page to make the buying buttons stand out more.

**Comment by calvincorreli** [comment]
What specific sections would you like this for? And if you can give me links to specific pages where I can see it, that would be super helpful. Thank you!

**Comment by ingjerd123** [comment]
Certainly

The section is "text and media"

This is my sales page:
https://norskgrammatikk.simplero.com/pages/supergod

This is one of my freebie pages:
https://norskgrammatikk.simplero.com/pages/gratiskurs
(yes, I know its a bit ugly still)

In this page I would like to have more than one button:
https://norskgrammatikk.simplero.com/

These are all made in Sites

What I wish, is that the color could be customized for every button I make in stead of using the button color for the site. I have a different color themes for my freebie (red/yellow) than for my paid product (blue/green)

I addition, it would be super wonderful if the button size (and text size on the button) also could be customized (made bigger)

Thank you so much for looking at this

**Comment by calvincorreli** [comment]
Color setting deploying now. We're not going to be doing size, but you could do that via CSS, or by using the theme editor, which will arrive very shortly now.

**Comment by ingjerd123** [comment]
Thank you so much for this! I'm using it already! :-)

Ingjerd
