### ISSUE TITLE
Custom CSS on website

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#36]
Hi! 

I have started making my website and sales page in Simplero (Site), and it looks really great, thank you so much for this new feature! I read on the help site that you plan to add the possibility to add your own CSS to the website, so the page is more customizable. When will that be possible ...? I'm very much looking forward to that, so I can make my own buttons etc. Then there will be no need for Instapage, Leadpages or other additional expenses, the Simplero website would be better!

**Comment by mjeeezey** [comment]
Yes! This would be awesome.

**Comment by calvincorreli** [comment]
Added now under Customize theme drop-down.
