### ISSUE TITLE
[footer] conditional content based on tags...

### ISSUE THREAD

**Issue by mortenspindler** [Simplero/Roadmap#360]
The feature discribed in a live facebookvideo that allows you to insert contact tags like:
{% if customer.tag_names contains 'My tag' %}
The contact totally has this tag.
{% else %}
Nope, the contact doesn't have the tag.
{% endif %}

– in emails etc is great, but it doesn't work in the footer section of lists, which would be very nice indeed

**Comment by calvincorreli** [comment]
Done now.

**Comment by mortenspindler** [comment]
wow
