### ISSUE TITLE
A picture - text - picture page section would be great

### ISSUE THREAD

**Issue by joyfuldoctor** [Simplero/Roadmap#370]
It would be great if there was a 'picture - text - picture' section option for pages in Simplero.
Please find attached a picture of the result I am trying to achieve.
Cheers, 
Tom @ Team Joy
![capture](https://user-images.githubusercontent.com/39340009/45631916-fb11b280-ba93-11e8-9303-eecee3396615.JPG)

**Comment by teresa-slp** [comment]
Yep! I would love to have this option! Please, please.... :)

I use that feature a lot on my current website and on the member site I'm transitioning to Simplero.

**Comment by calvincorreli** [comment]
Done.
