### ISSUE TITLE
Add one field to email templates

### ISSUE THREAD

**Issue by PlanetThoughts** [Simplero/Roadmap#374]
The Simplero email template has a big missing feature: the body. In MailChimp, Constant Contact, 1ShoppingCart, and every other email system I have used, templates include the body field. There are good reasons for that. Here are a few:

1) Across multiple templates, the user may have (for example) a single-column format and a double-column format, used for differing purposes. In each of those, the template's body field would include the HTML for the body and the columns, and the standard title format for each column. For one client, we used to have a single-column and double-column layout, and for each of those, there was a version that had space (and font characteristics) for a quote at the very top of the broadcast, or no quote. That is just an example.
2) Currently there is no way to have a standard signature automatically included. One has to remember to copy and paste it from previous broadcasts (or some similar method that is error-prone and requires training others on another step or two).
3) To set standards for multiple individuals in an organization, as well as for any contractors helping to prepare email, it is useful to have a standard body (or bodies if there are >1 template) that includes the style information for the organization's emails.

**Comment by PlanetThoughts** [comment]
Has anyone read this request? Any thoughts about it? It is easy to implement, perhaps easier than it appears. Add an editable field in the template interaction, and when starting an email from a template, include the Body HTML from that editable field. For pre-existing templates from before this feature is implemented, the Body field of the template would simply be empty (until when and if the user wants to have content in the template Body).

**Comment by calvincorreli** [comment]
We see all of the requests, but don't necessarily respond to all of them.
