### ISSUE TITLE
Auto-add to the house list for activities such as product purchases

### ISSUE THREAD

**Issue by PlanetThoughts** [Simplero/Roadmap#383]
This is a pretty fundamental feature. Currently, every time a new product is created, the creator needs to remember to add a trigger that subscribes the product purchaser to the main (house) email list. The same is true of people completing sign-up forms and other engagement activities. There should be a global setting regarding this, and there are various ways to implement it. 

Simplest would be a global setting that could either be left blank and would lead to the current behavior of setting up a list add for each product and transaction, or if a list name were selected, then every product purchase and other transaction would automatically add the contact to the selected list (with options on welcome email and auto-responder). 

A more thorough implementation would have a different default list for each type of transaction (product, sign-up form, etc) since they might want a different list for each different kind of transaction. And with each product and form, there would be an option to override the default behavior.

**Comment by calvincorreli** [comment]
I'm confused.

Can you reach out to support about this, please?

Subscribing to the main list is exactly what happens when you purchase a product and check the box. And there's an option on the Product > Order form for which list they should be subscribed to.

**Comment by PlanetThoughts** [comment]
I was under the impression that people would be subscribed to the list selected in the order form setup, even if they were not given the checkbox. Perhaps it seems unfair to add them to a list without always telling the client, but the same thing is accomplished by manually adding, for every product, a trigger that adds them to the list without their knowledge. It is just harder to do and requires remembering to do this for every product and form. By the way, for free or low-cost items, the user is told on the page that if they do the free or low-cost download/purchase, they will be added to the list. Do you feel it is unethical to add them to a list without saying so if they buy, for example, a $397 class? Thoughts?

**Comment by calvincorreli** [comment]
Yes. Honor the checkbox. We do let you have it pre-checked.
