### ISSUE TITLE
I want to be able to edit the 'Not Found' page

### ISSUE THREAD

**Issue by joyfuldoctor** [Simplero/Roadmap#384]
Hello
I want to be able to edit the 'Not Found' page.
The generic version does not match our website theme.
Cheers
Tom @ Team Joy
![capture 3](https://user-images.githubusercontent.com/39340009/46538044-d0ed2c80-c8aa-11e8-9945-22d40eae5ac4.JPG)

**Comment by calvincorreli** [comment]
Go to site theme, edit code, then find templates/404.liquid, you can edit it to your heart's content.

**Comment by joyfuldoctor** [comment]
Hi Calvin


Thank you for your reply.


I have looked at editing the templates/404.liquid code, but my coding knowledge is minimal and I am nervous of causing more problems than I solve.


I was hoping it would be possible to edit the page in the same way as we edit the pages on our Simplero site.


Best wishes


Tom @ Team Joy


www.joyfuldoctor.com<http://www.joyfuldoctor.com>


Tel: (+44) 1932 922100


[1516278997738_PastedImage]



________________________________

**Comment by calvincorreli** [comment]
That's a great idea!

**Comment by calvincorreli** [comment]
This is now deployed. Go to Site > Configure > Advanced, and you can choose a page on your site to use for "404 Not Found".
