### ISSUE TITLE
Unable to delete batch of emails

### ISSUE THREAD

**Issue by drjesshouston** [Simplero/Roadmap#385]
After sending out an email, you can see who has unsubscribed. You can also the emails that bounced. However, upon clicking the dropdown box, there is no option to delete. This means that you must delete the contacts one by one. This is very time consuming.

**Comment by calvincorreli** [comment]
Why do you want to delete them?

**Comment by drjesshouston** [comment]
I delete the email addresses, because I do not want to continue emailing
the email addresses that bounce or unsubscribe. Maybe I did not explain
what is happening correctly.

Warm Regards,

Dr. Jessica McSheck Houston
Licensed Social Worker
Author/Trainer/Consultant
http://expectingvictory.com/

**Comment by calvincorreli** [comment]
But if they bounced or unsubscribed, then they'll automatically be not emailed to in the future. No need to delete them. It's all taken care of automatically for you.
