### ISSUE TITLE
Statistics overview in Automations

### ISSUE THREAD

**Issue by mortenspindler** [Simplero/Roadmap#40]
it would be nice to have an overview of statistics like open/click-rates for the Automations, like you have in autorespones.

![autorespons-statistic](https://cloud.githubusercontent.com/assets/28627953/25953748/96687440-3664-11e7-9735-e4b049144585.jpg)

**Comment by ManjirS** [comment]
Second this. Be great to have stats from emails in the entire email library on the dashboard.

**Comment by calvincorreli** [comment]
Hey Morten, didn't even realize you were the one that requested this originally. It has been done now!
