### ISSUE TITLE
see title of email in automations activity flow

### ISSUE THREAD

**Issue by teresa-slp** [Simplero/Roadmap#403]
After using nothing but auto-responders, I'm trying to get used to automations. 

The displayed "flow" of step/number system in automations is not very helpful because it looks like no emails were delivered at all.

For example, it shows step 10 (add a tag) and step 12 (wait 1 day) as completed, but never indicates step 11 (the email with title x,y,z) was delivered.

Can you please make it so the title of the automated email appears as one of the steps in the flow screen so we can see exactly what was delivered without clicking on the subscribers specific profile page? 

Thanks!
Teresa

**Comment by calvincorreli** [comment]
That's a bug with how the flow progress is being logged. The action steps are being logged as the wait step before them. I'll fix that now.
