### ISSUE TITLE
Styling for worksheets

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#404]
We don't currently have an option to style or use CSS on Worksheets.

I would like to apply a bit of styling to worksheets, to better separate the text boxes that people can write in, from the background.

Also the ability to style spacing, put boxes around questions, adjust placement of multiple choice options, could be possible enhancements that would enhance the usability and make worksheets more intuitive to read.

**Comment by ellanylea** [comment]
I second this feature. These days, with the elegance and user friendliness of TypeForm and Qzzr or Interact Quiz, I'd highly support this feature request.

Even something as simple as a big textarea, where the handwritten CSS we type in is applied to the worksheet. I love Email Template and Membership Template, which didn't exist when I first joined, but as a former PHP developer and UX designer, I know that feature requests take time. 

So truly, just a big old textarea for handcoded CSS would be fabulous! Thanks!

**Comment by calvincorreli** [comment]
I'd rather improve the design of the existing thing, at least do that first. We're working on that.

**Comment by ellanylea** [comment]
> I'd rather improve the design of the existing thing, at least do that first. We're working on that.

Do you have an estimate date of when the existing design can be improved? I may time my next masterclass launch based on this feature and move my TypeForm forms into Worksheets in this case. Thanks, Calvin!

**Comment by calvincorreli** [comment]
This is NOT a promise of anything, but we have just hired a designer, and this is currently on our agenda for our next 6-week cycle starting on Monday. I think that's as close as I can get to answering. Again, this is NOT a commitment on our part, just a statement of intention.

**Comment by ellanylea** [comment]
Understood, I get the world of dev/UX :) And thank you for this honest,
kind response.





*Ellany Lea* • CPCC, PCC, CDWF, CDLF

🌹 Founder, Guide to Grace
🏆 Success Coach • Psychotherapist • Lifestyle Mentor
🌎  117/193 Countries

www ellanylea.com  •  fb @EllanyLea <https://www.facebook.com/EllanyLea>  •
 ig @EllanyLea <https://www.instagram.com/EllanyLea>

**Comment by tueolesen** [comment]
New layout of worksheets has been much improved.

CSS can be styled on the account-wide Custom CSS settings, which affects all worksheets across every membership site. Probably OK for now :-)
