### ISSUE TITLE
Photo gallery 

### ISSUE THREAD

**Issue by Dancekidscanada** [Simplero/Roadmap#414]
I would love to add a photo gallery. 
Thanks

**Comment by emilyannpeterson** [comment]
Bonus points if this photo gallery is viewable on other pages! Triple bonus points, if that view is modifiable and beautiful! 

i.e. Photo Gallery of all my "As Seen In" publicity logos could be easily featured on multiple pages of a site. As it stands now, I have to create each "As Seen In" logo collection from scratch for each page.
