### ISSUE TITLE
Folders for media

### ISSUE THREAD

**Issue by Dannooo** [Simplero/Roadmap#42]
Now that I have 100s of images, videos, pdfs, it would grand to have some organization to make them easier to find.

**Comment by cipriansoleriu** [comment]
yes! same for automatinos

**Comment by SarahEKerr** [comment]
Yes to both of these!

**Comment by calvincorreli** [comment]
We're considering a system where you can add labels to all kinds of things in the admin interface, and that way also see everything that's labeled with that label across the admin UI.

**Comment by calvincorreli** [comment]
I'm going to close this one. We have this on the roadmap.
