### ISSUE TITLE
Tagging members in forum

### ISSUE THREAD

**Issue by JesperChristophersen** [Simplero/Roadmap#431]
We´d love to be able to “tag” members in the forum (we´re still using the old forum from our old space) so the “tagged” member receives an email, letting him or her know, that his / her name has been mentioned in a conversation.

**Comment by calvincorreli** [comment]
We're not going to add that to Spaces.

What would it take to get you guys moved over to using Membership sites?

**Comment by JesperChristophersen** [comment]
We have moved to Membership sites long ago, - everything except our forum and the only reason is, that it is not (yet) possible to transfer the content from our space forum to our new membership site forum. We´re still hoping very much for that option, because we have so many good dialogues in our space forum that we need to keep. :)

**Comment by calvincorreli** [comment]
Got it. If we could figure out how to move the actual posts to a membership site, does the way forums currently work in membership sites work for you, or would we also need to make changes to how they work?

**Comment by tueolesen** [comment]
@calvincorreli i'm in the same boat as @JesperChristophersen  here -- a way to move forum posts, would also allow me to make the final move to 100% membership sites.

**Comment by calvincorreli** [comment]
That would be great, yes. We plan on adding the Like feature to membership sites shortly.

You can have categories, but only one flat level. You can't do permissions per forum categories, as far as I know.

As for style, we can look at that. We just hired a designer. I'm pretty excited about that, actually.

**Comment by JesperChristophersen** [comment]
Brilliant if the like-feature is coming soon to the membership site forums.

I just checked and yes – categories work just fine in the new forums. No sub categories though, as you mentioned, we´ll just have to manage without that, - no problem.

Sounds great with a designer, - now I´m excited about that as well.

It does sound a lot like you might be able to make a solution for us to bring over the old forum content to our membership site – am I right? :)

**Comment by calvincorreli** [comment]
That's the plan, yes.

**Comment by JesperChristophersen** [comment]
Awesomesauce 🥇
