### ISSUE TITLE
Copy sections

### ISSUE THREAD

**Issue by jesperconrad** [Simplero/Roadmap#434]
Can we get a duplicate section?

I use headers, I style the same, and it would save so much time. The same goes for enroll now buttons etc. So many things where I am happy with the styling I have made, and then I need to do it all over again, as I cannot copy a section...

Pretty please :)

**Comment by BethKBJ** [comment]
Hi Jesper,
I love this idea!  Thanks for writing it up.  
Beth

**Comment by calvincorreli** [comment]
Our thinking is you'd "save as template", and then when you add a section, you can add from your template library, or add a new one.

Does that sound like it'd do the trick?

**Comment by jesperconrad** [comment]
Save as template would be awesome /)

Mvh

J.F. Conrad

**Comment by ingjerd123** [comment]
This is implemented now, but I notice one cannot use a saved template from "website" and use it on a membership site. That would be cool too. I'm making a demo membership site and I want to duplicate the testimonials section from the sales page and use it in the demo site to increase sales

**Comment by calvincorreli** [comment]
They're tied to the theme. If you're using the same theme on both sites, you should be able to.
