### ISSUE TITLE
Extend broadcast name on product summary view

### ISSUE THREAD

**Issue by nichart** [Simplero/Roadmap#438]
I would really like it if you would extend broadcast name to more characters, so you could see more on the broadcast name. On my screen there a twice the space for the name. I sted of 27 characters, could there be 50 or 60?
![noglen til dit temperament nto1 foraeldresparring dk s simplero](https://user-images.githubusercontent.com/4003363/50593221-c802fb80-0e97-11e9-84ef-cb4ee60391c5.png)

**Comment by calvincorreli** [comment]
Really good point. An improvement is out now. Thanks for the suggestion!
