### ISSUE TITLE
Podcast-link on iPhone for outside US users

### ISSUE THREAD

**Issue by hartmanncreate** [Simplero/Roadmap#441]
I have been told by Simplero customer service that the issue with the podcast-link not working for non-US users on iPhone, is an Apple issue. But this is a mayor inconvenience for us! 

Even though we have the work-around with the 'Hold down your finger' written multiple places on our member site, we get a lot of messages and mails about this issue. People are questioning our choice to use Simplero.  

Please let us know that you are working on a solution?

**Comment by calvincorreli** [comment]
I haven't been able to find a solution for this.

It's really stupid. It's just a matter of ... which protocol to use (rss://, feed://, http://, or some other protocol), whether the URL needs to end in something specific (.rss, .xml, or it doesn't matter), and maybe something about the Content-Type we send it with (don't think it should matter), or if there are some things about the content (shouldn't be, that part's standardized.)

I've spent hours searching Apple's developer documentation and the web in general trying to figure out how it's supposed to be, and come up empty-handed. So it's pure guesswork.

If I figure out how it's supposed to work, the fix takes less than 17 seconds. It's not hard at all.

If you have examples of podcast links that ARE working, please send them our way. We've wasted hours and hours on this getting nowhere.

**Comment by nichart** [comment]
Still no solution for this?

**Comment by nichart** [comment]
This is still a mayor issue for us.

**Comment by nichart** [comment]
Hi Calvin

This issue is still very annoying. 

Lately I have been advisering customers to copy the podcast links on their computer or mac, save the somewhere where they access them from their iPhone and copy them into the Podcast App. 

There must be a way for you to solved this?

Kind regards
Nick

**Comment by nichart** [comment]
The work-around with the 'Hold down your finger' doesn't work anymore on the latest iPhone updates. The option to copy doesn't come up.

**Comment by brassrabbit** [comment]
This is solved now.

**Comment by midnightmonster** [comment]
Should be solid now.
