### ISSUE TITLE
Ability to Designate any page as "homepage" without needing to recreate that page from scratch.

### ISSUE THREAD

**Issue by emilyannpeterson** [Simplero/Roadmap#444]
Hi Simplero!

I'd love the ability to designate any page as "homepage" without needing to recreate that page from scratch. sometimes it takes a long time to build a page and recreating that page is super annoying when you realize you didn't start building that page on the default homepage to begin with. <facepalm>

thanks!

**Comment by calvincorreli** [comment]
You can already do that, right? Just go to Site > Configure, and third field down from the top is which page to use for home page.

**Comment by emilyannpeterson** [comment]
Awesome! I didn't know that was there... Perhaps it would be best housed under the "Navigation" tab rather than Configure?

Regardless, thanks!

**Comment by calvincorreli** [comment]
I can see that.
