### ISSUE TITLE
Blog: more than 1 category

### ISSUE THREAD

**Issue by coachjan** [Simplero/Roadmap#451]
Hey

It would be nice if I could select more than 1 category for an article. 
This way I can select my podcast as a category, but also the subject.

kind regards 
Jan

**Comment by calvincorreli** [comment]
What do you mean select my podcast as a category?

**Comment by coachjan** [comment]
Thank you for your response!

I write articles and have a podcast. I publish an episode on the website via a blog article and want to distinguish these articles from the regular articles via the category "Coach Jan Podcast". So 2 (or more categories) per article would be useful.

You can see it here: http://www.coachjan.be/blog

**Comment by calvincorreli** [comment]
So you only want certain blog posts to be included in the podcast?

Even some blog posts that would have an audio file attached, you don't want them to show up in the podcast feed, correct?

Do you have more than one podcast from the same block?

**Comment by calvincorreli** [comment]
I don't see us doing this anytime soon, unless it's something that a large number of other people have a major use case for.

**Comment by coachjan** [comment]
I understand that! Thanks
