### ISSUE TITLE
Worksheet conversation on and off

### ISSUE THREAD

**Issue by CoachWouter** [Simplero/Roadmap#453]
The fantastic worksheet conversation feature is now turned on by default. This is great for courses where such interaction with the client is part of what they pay for. However, for self-directed courses without interaction, the conversation box in the worksheet creates an expectation that we cannot fulfill. So it will be helpful if we can turn this feature off when that is appropriate.

**Comment by calvincorreli** [comment]
I'm pretty sure it only shows up if an admin initiates the conversation.

**Comment by CoachWouter** [comment]
Hi Calvin,

Thanks, this request followed a conversation with your support team.

Please double check to be sure and let me know?

Kind regards,

Wouter

**Comment by calvincorreli** [comment]
I've already checked. Who did you talk to on our support team?

**Comment by CoachWouter** [comment]
Hi Calvin,

Thanks. I had a helpful exchange with Karen Murphy on your team.

Kind regards,

Wouter
