### ISSUE TITLE
Phone number mark-up

### ISSUE THREAD

**Issue by casvos** [Simplero/Roadmap#458]
It would be very handy if clicking on a contact's phone number should start a call from the computer (I use this feature all the time from other applications with my Mac+iPhone combo). However, the phone number is marked-up in the format of "callto:NNN..." and this doesn't trigger a phone call. At least not in a MacOS (Swedish) environment (I don't know about other languages). It should be "tel:NNN..."

Referring to this discussion thread ... https://stackoverflow.com/questions/1164004/how-to-mark-up-phone-numbers ... it seems as "tel:" is the right way to go for phone calls. 

Suggestion: Either change the "callto:" to "tel:" or make it possible to choose.

**Comment by calvincorreli** [comment]
Great. Consider it done. Thanks for the suggestion.

**Comment by casvos** [comment]
Wow, thank you so much for this super fast solution of a minor "nice-to-have" suggestion!
I will post another suggesten right away, a much more important one ...
