### ISSUE TITLE
Support for fontawsome needed

### ISSUE THREAD

**Issue by casvos** [Simplero/Roadmap#461]
I use special icons in my present website and would like to use it in Simplero as well, both in text and Buttons etc.

Any thought about making this happen in the near future?

https://fontawesome.com

**Comment by calvincorreli** [comment]
I believe you should be able to add this by editing your site theme's code. Just add the LINK tag to your layout/theme.liquid file.

https://fontawesome.com/start

I don't think it's something we want to add to all sites by default.

**Comment by casvos** [comment]
Hi,

I followed your instructions and checked those on fontawesome’s website as well, and put the correct link tag in layout/theme.liquid.

Unfortunately, this doesn’t work. 

When inserting icons, e.g. <i class="fas fa-igloo"></I>, in the html of a Simplero page or anywhere in Simplero, it gets deleted.

//Carl

**Comment by calvincorreli** [comment]
It looks like you're closing the <i> tag with something other than </i>.

Is it a lowercase "L"? It needs to be the same thing.

**Comment by casvos** [comment]
Sorry, it’s just a typo. The closing is an lowercase i

**Comment by calvincorreli** [comment]
Send me a link to the page, please.

**Comment by casvos** [comment]
https://new.humanawareness.se/test-page

I’ve tried to insert different Fontawsome icons on this page in the html code of the text section, but the code just disappears.

**Comment by calvincorreli** [comment]
I see. The TinyMCE editor is a little aggressive in replacing `i` tags with `em` tags, and then removing empty `em` tags.

This is a work-around that gets the job done:

```
<span class="fas fa-igloo">​&#8203;</span>
```

It uses the span tag option, and then includes a "zero-width space" so that TinyMCE won't remove it.

**Comment by casvos** [comment]
Thank you sooo much for your help!

I wish you a great day!
