### ISSUE TITLE
without www site is not working

### ISSUE THREAD

**Issue by Yogeshhirau** [Simplero/Roadmap#463]
I have contact to the godaddy and they said problem is with the hosting end they said please add htaccess file to the hosting end write redirect code there for redirect https://salubriousjuiceandmore.com to https://www.salubriousjuiceandmore.com

because https://salubriousjuiceandmore.com is not working without www.

**Comment by calvincorreli** [comment]
Our hosting doesn't have a fixed IP address, so you need a CNAME record, not an A record in DNS.

Unfortunately, CNAMEs can only be done on a subdomain.

I'm not aware of any way around this.

PS. They don't know what  we're talking about. We're not using Apache, don't have no htaccess files.

**Comment by Yogeshhirau** [comment]
is there any way to run this https://salubriousjuiceandmore.com/

**Comment by calvincorreli** [comment]
We would have to handle name servers for you, and we can't do that at the moment.

**Comment by Yogeshhirau** [comment]
Can you tell me how much time would it take to resolve the issue, how much days, I am going to lost my customers due to this issue.

**Comment by Yogeshhirau** [comment]
?

**Comment by calvincorreli** [comment]
It's not something we'll do any time soon.

This is absolutely possible to get working with Godaddy, so they redirect the non-www URL to the www-URL and we host the www-URL. That's the only way I know of to get this working.
