### ISSUE TITLE
Show where library emails are used

### ISSUE THREAD

**Issue by Siiffloor** [Simplero/Roadmap#469]
I have a hard time remembering where I used my different library emails.
Some are used in Automations, some as triggers and others has never been used anywhere.

It would be a great help if each Library email would show links to the automation or trigger that are connected to the library email.

It would fit perfectly in the right sidebar of the email (in the same way as the automations are linking to the places that are starting and stopping the automation).

Thank you in advance
Siif

![image](https://user-images.githubusercontent.com/33745310/53089659-7973f400-350d-11e9-8cde-a94a7d0b6f34.png)

**Comment by ingjerd123** [comment]
I was just gonna write this request. But I see you made it already.
I have 100 000 000 library emails, so I vote for this!

**Comment by ingjerd123** [comment]
I see you have implemented this now. Thanks a lot for this feature. :-)

The library emails also show up as used in deleted automations. Could those automations have a parentheses or something that says they are deleted?

**Comment by calvincorreli** [comment]
Good point. Fix coming out shortly.
