### ISSUE TITLE
Remove "Your sites" completely - redundant

### ISSUE THREAD

**Issue by emilyannpeterson** [Simplero/Roadmap#473]
![image](https://user-images.githubusercontent.com/307176/53302386-48543600-3823-11e9-965a-d4c9ff8f6a94.png)

Since users/visitors/customers can access "their sites" by logging in and click "my account": 
![image](https://user-images.githubusercontent.com/307176/53302449-b862bc00-3823-11e9-80b8-8f8b8e99b49b.png)

Their Membership site access is the first thing that shows up on that page, as seen here:
![image](https://user-images.githubusercontent.com/307176/53302436-9701d000-3823-11e9-87ac-805c729eb2d9.png)

I vote that we create the option to remove "Your Sites" completely from the navigation of membership sites altogether.

**Comment by calvincorreli** [comment]
I tend to agree with you that the "Your Sites" menu is not all that well thought through. It was carried over from Spaces.

It might be as simple as just getting rid of it completely.

I prefer not to create options when it's better to just do the right thing out of the box. If anyone REALLY wants this back, we can always provide you with the code snippet for you to do it in your own theme, but I doubt it.

**Comment by tueolesen** [comment]
My vote for removing it completely - on my sites, i've been hiding it with CSS so far.

**Comment by emilyannpeterson** [comment]
Yay for removing it completely!
