### ISSUE TITLE
zapier: zap for tags

### ISSUE THREAD

**Issue by Dannooo** [Simplero/Roadmap#48]
Would love to have a zap triggered by tags being added or removed.

**Comment by calvincorreli** [comment]
Added/removed from a contact, I'm assuming ...

**Comment by themanagementcoach** [comment]
I'd also like to see a zap be able to apply a tag when creating/updating a contact. Right now you can only add a tag from Subscribe to a List (and even that isn't pulling up the Simplero tags that are available so you have to type it in manually)

**Comment by nickbruun** [comment]
This is now implemented and available in Zapier :)
