### ISSUE TITLE
Add course title to the course comment grid

### ISSUE THREAD

**Issue by ShivanSarna** [Simplero/Roadmap#483]
We would like to turn on the comment feature for our live courses, but we noticed that when looking at the comments the list is of all comments across all courses, but the course title is missing from the grid?!?

I expected to see a list of all the comments for all the courses with a column for the course title so we could differentiate between the courses as we use the lesson title to provide direction to the end user. 

Please allow us to add course title to the grid.

See screenshot attached.

**Comment by calvincorreli** [comment]
Good point. We should have that change deployed tomorrow.
