### ISSUE TITLE
The Catalog Overview lists all products using external product names (not internal names)  This makes the overview hard to figure out when products have similar names (i tend to differentiate them on the internal name)

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#488]
Under Products > Catalog, the Catalog Overview lists all products using external product names (not internal names)

This makes the overview hard to figure out when products have similar names (i tend to differentiate them on the internal name)

I suggest changing the Catalog Overview to use Internal Product names instead.

Thanks.
Tue

**Comment by calvincorreli** [comment]
That's a really good point. Let me fix that  right away.

**Comment by calvincorreli** [comment]
Done.

**Comment by tueolesen** [comment]
That was fast :-) Awesome! Thanks!
