### ISSUE TITLE
Usability: Different colors on Submit Button / New Post Button in Forum

### ISSUE THREAD

**Issue by tueolesen** [Simplero/Roadmap#498]
In the membership site forum, when writing a new post, there are two buttons:
"Submit post"
"Create new post"

(they are translate in danish)

with the same color/size and with wording that could be mis-interpreted, i have experienced (first hand) confusion: 

When i'm done writing a new blog post, i instinctively click the upper right button to create a new post, which then discards all my writing...Bummer!

<img width="965" alt="Skærmbillede 2019-05-16 kl  08 34 03" src="https://user-images.githubusercontent.com/16045305/57831914-ae16e500-77b6-11e9-9a32-a7c1739e4db5.png">

What i SHOULD do is click the lower left button, but my eyes totally miss it and i get no warnings like "are you sure you want to discard your current post?" before it just happens. Anyone out there who can recognize this?

Suggetions for improvement:

- Make the relevant button GREEN or some bright color
- Ask the user if they are sure before navigating away from the post editor.
- Entirely remove the "Create new post" upper right button - that's not what we want people to do when they are already doing exactly that, and we want them to finish what they are doing.

Best regards,
Tue

**Comment by calvincorreli** [comment]
Yeah, I think we should just remove that button on that page. I'll let the team know.

**Comment by tueolesen** [comment]
Thanks @calvincorreli  - Awesome!

**Comment by tueolesen** [comment]
This has been fixed now - the "new post" button is removed!
