### ISSUE TITLE
Favorit funktion

### ISSUE THREAD

**Issue by Livskvalitetspartner** [Simplero/Roadmap#56]
Jeg bruger simplero til min streaming tjeneste - et kæmpe arkiv med flere 100 hypnose og meditations filer som folk får adgang til. 
Jeg vil gerne have en favorit funktion, så mine abonnenter kan markere de lydfiler de ønsker at bruge for senere at kunne finde dem under deres favoritter. ( Ønsker at høre senere.) Lige som man kan når man finder en god film i Netflix, som man gerne vil se en anden dag.

**Comment by calvincorreli** [comment]
We appreciate the input, but please keep this forum in English, so everyone has a chance to participate. Thank you.
