### ISSUE TITLE
Nye lydfiler funktion

### ISSUE THREAD

**Issue by Livskvalitetspartner** [Simplero/Roadmap#57]
Jeg bruger simplero til min streaming tjeneste - et kæmpe arkiv med flere 100 hypnose og meditations filer som folk får adgang til. Der uploades løbende nye lydfiler og de bliver altid lagt ind på allerede eksisterende sider sammen med andre lydfiler i samme enme. Derfor er det besværligt at følge om der er kommet nye lydfiler. 

Jeg vil gerne have en funktion som gør at hvis jeg uploader en ny lyddil eller video på en allerede eksisterende side -  så kan jeg tjekke en boks af som gør at mine abonnenter kan se den nye lydfil på en liste over de 50 nyeste lydfiler eller videoer.

**Comment by calvincorreli** [comment]
We appreciate the input, but please keep this forum in English, so everyone has a chance to participate. Thank you.
