### ISSUE TITLE
søgefuntkion og tags 

### ISSUE THREAD

**Issue by Livskvalitetspartner** [Simplero/Roadmap#58]
Jeg bruger simplero til min streaming tjeneste - et kæmpe arkiv med flere 100 hypnose og meditations filer som folk får adgang til. Lydfilerne er fordelt i emner som angst stress negative tanker osv og jeg forsøger altid at lægge hver lydfil på den side hvor det giver mest mening. MEN mange lydfiler kunne lige så godt vore tilknyttet flere emner. Feks, kan en lydfil være egnet både ved stress og angst. 
Derfor ønsker jeg mig at simplero udbygges så det virker lidt i stil med netflix og viaplay, hvor man lægger filerne i et bestemt afsnit. Feks, angst / Action film. Men at der samtidigt er mulighed for at man tilknytter op til 10 tags til hver lydfil så der også kan søges på emne / tag. 

Altså: Feks, kan en spillefilm på netflix både have tagget actionfilm og kærlighedsfilm og så vil den komme frem på listen både hvis man søger på det ene og hvis man søger på det andet. 

Det samme ville jeg ønske man kunne med mine lydfiler. At jeg kunne tildele hver enkelt nogle tags så de kommer frem når der søges på det tag.

**Comment by calvincorreli** [comment]
We appreciate the input, but please keep this forum in English, so everyone has a chance to participate. Thank you.
