### ISSUE TITLE
create new tag in Add new trigger popup

### ISSUE THREAD

**Issue by andersronnau** [Simplero/Roadmap#6]
If I am adding a trigger while editing a price, and I want to add a tag to the person buying the product, I would like to be able to create an entirely new tag while I adding the trigger. 

Now I have to cancel the add new trigger, go back to the tags section, add the tag, reload the price, add new trigger and then find the new tag.

Small thing, but great for workflow while setting things up for the unorganized that don't create new tags before creating the prices. 😃

**Comment by calvincorreli** [comment]
You can already, actually. Just start typing:

![Create tag in Trigger dialog](https://d3vv6lp55qjaqc.cloudfront.net/items/180V1A0h3X1B0J0N0M06/Screen%20Recording%202017-04-05%20at%2010.30%20AM.gif)

I've added a help text to make that more obvious.

Try it in other tag select boxes, too. Should work everywhere, unless we've missed one.

**Comment by andersronnau** [comment]
Sweet! So obvious I didn't realize it. 😃
