### ISSUE TITLE
Order Bump suggestion

### ISSUE THREAD

**Issue by cipriansoleriu** [Simplero/Roadmap#60]
Great idea introducing order bumps!!

I'd like to come with some suggestions. 
- make it more visible, not a simple check next to the terms and conditions 
- when someone clicks it, reflect the total value to be paid in the form where he enters his car number

as a suggestion, try to make it look similar to this screenshot from clickfunnels - it is proven to work very well ...

![image](https://cloud.githubusercontent.com/assets/3611728/26739134/5f51f04a-47d9-11e7-8ef5-2314b6cba014.png)

**Comment by cipriansoleriu** [comment]
Update on **when someone clicks it, reflect the total value to be paid in the form where he enters his card number.**

right now the client has no ide how much he'll be charged:

**without order bump**
![image](https://user-images.githubusercontent.com/3611728/27034344-eeff743e-4f85-11e7-9961-e77f46544676.png)



**With order bump (nothing changes)**
![image](https://user-images.githubusercontent.com/3611728/27034355-f8aa88a2-4f85-11e7-993b-891feb9a6c3e.png)

**Comment by calvincorreli** [comment]
The second part was done a long time ago.

Today we rolled out a new sexier design for order bumps, along with the ability to pick your own color, and add more copy to make it more enticing.

We hope you like it.

**Comment by cipriansoleriu** [comment]
sexy !! :):) 👍
