### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#65]
It would be awesome if Simplero could have som sort of statistics on subscribers, for example how many percent opens all the emails in an automation, for example. Don't know if it is possible, but it would be great

**Comment by calvincorreli** [comment]
What exactly would you like to see?

How many opened ALL the emails?

Remember, open rates are basically meaningless OTHER than to compare between two subject lines sent around the same time to the same audience.

**Comment by calvincorreli** [comment]
No answer.
