### ISSUE TITLE
Different language for different offers

### ISSUE THREAD

**Issue by NancyBatens** [Simplero/Roadmap#66]
I started working in English (and have 1 space in English) but am now also creating things in my native language (Dutch). It would be nice to be able to choose the language (and possibly also some other lay-out (linked to other website) but that's less important) in function of the product/space.

Thanks!

**Comment by calvincorreli** [comment]
Language is based on the setting in the user's profile.

You can also add a ?locale=nl or something similar to any URL, and it'll force the locale to what you say.

**Comment by NancyBatens** [comment]
Thanks, Calvin!
Nancy
