### ISSUE TITLE
Suggestion: hiding products etc. when selecting recipients for a broadcast

### ISSUE THREAD

**Issue by ingjerd123** [Simplero/Roadmap#67]
Every time i'm about to send a broadcast I get a bit worried that I will send the broadcast to the wrong list/product/segment/tag because I have so many.

If you could make it possible to hide products etc. when selecting recipients in broadcasts, that would be great. :-)

**Comment by calvincorreli** [comment]
This is exactly what the stars do on the right hand side of the lists of Lists, Products, Spaces. We don't do it for Tags or Segments, that's right.

**Comment by ingjerd123** [comment]
Ah, that is great! I didn't know, thank you
