### ISSUE TITLE
Personalize Currency in Third Party Sales Tracking Code

### ISSUE THREAD

**Issue by andersronnau** [Simplero/Roadmap#7]
I sell in two currencies (USD and DKK) and would like to use that information in my Facebook ads campaign tracking.
Right now I can't select Currency as a "Personalize" option.
If I can do that, the FB Event pixel can handle the rest.

<img width="534" alt="skaermbillede 2017-04-05 kl 12 19 45" src="https://cloud.githubusercontent.com/assets/26906975/24701384/8dcdbb64-19fa-11e7-8a72-af02adaec016.png">

**Comment by calvincorreli** [comment]
It's actually working, as {{currency_code}}. 

I'll update the drop-down so it's included there as well. That's an oversight. Thanks for letting us know.
