### ISSUE TITLE
Unsubscribe Process Looks very confusing - Can it be simplified?

### ISSUE THREAD

**Issue by desireeeast** [Simplero/Roadmap#70]
I recently had a small number of very loyal subscribers and participants from a recent course unsubscribe from my list (which surprised me), and I'm wondering if the unsubscribe process had anything to do with it... (I uploaded a video in the Simplero FB group: https://www.facebook.com/groups/simplerousers/permalink/1396699867075813/?comment_id=1397249570354176&ref=notif&notif_t=group_comment_mention&notif_id=1498213015433101)

The unsubscribe process looks very complicated compared to other email platforms. I went to test it, and there are too many buttons and radio buttons to choose from. I almost made the mistake of clicking the bottom red button that says, "Never email me again" and was confused as to which button to click to unsubscribe to a specific list.

It would be great if we are able to clean this up so that it's more clear (for us and our customers).
Thank you! 😊

**Comment by calvincorreli** [comment]
Interesting. If you come to it from an email, there's a button right up top that says "Unsubscribe" which will unsubscribe from whatever list or product was responsible for this person receiving this email.

Do you not see that?

I'm sure we could improve on this page, I'm not saying we couldn't.

**Comment by desireeeast** [comment]
Yes, I see it clearly. However, I got confused when I saw all of the other
radio buttons that are listed from being subscribed to other lists...so as
I scrolled through the other lists, I saw the 'Never email me again' button
at the bottom and got confused, because I thought it was the same button as
the top. But it's not. So, which button would I click on if I wanted to
choose which lists to stay on?

**Comment by calvincorreli** [comment]
To unsubscribe from what gave you this email: The top button.

To see what exactly you're subscribed to and choose what to stay subscribed to: The middle.

To unsubscribe from everything, now and in the future: The bottom.

**Comment by desireeeast** [comment]
Thanks Calvin, I understand how it works...I think it could be improved,
simplified or streamlined, aesthetically wise. Thank you for your response
and consideration. :)

**Comment by calvincorreli** [comment]
Ok. I was just answering your question "So, which button would I click on if I wanted to
choose which lists to stay on?".

**Comment by themanagementcoach** [comment]
I find it quite confusing as well, especially because the question as to whether they want to never receive emails again us underneath the unsubscribe button, with a large space in between. My suggestions to keep it simple are outlined on the attached images.
![screen shot 2017-10-03 at 2 56 01 pm](https://user-images.githubusercontent.com/32145688/31147642-814ccbc2-a858-11e7-8dca-c99dc37f2b86.png)
![screen shot 2017-10-03 at 2 56 11 pm](https://user-images.githubusercontent.com/32145688/31147641-8147efbc-a858-11e7-8435-8b55ebe4358a.png)

**Comment by calvincorreli** [comment]
Simplified.
