### ISSUE TITLE
Order Form - Instalments

### ISSUE THREAD

**Issue by Lyv** [Simplero/Roadmap#71]
When showing payments in installments, instead of stating 
400 EUR including VAT upfront, then 3X400 euros including VAT etc = 1200 EUR including tax total
Simplify with : 4x400 EUR Tax Included (1600 EUR tax included) (all on one line)

And then keep the breakdown with the table etc.

Example : https://lyviacairo.simplero.com/purchase/63629-Money-Money-Money-Saison-2

**Comment by calvincorreli** [comment]
Implemented now. Thanks for the suggestion. It's a great one!

**Comment by Lyv** [comment]
Thanks :)

2017-06-29 15:09 GMT-04:00 Calvin Correli <notifications@github.com>:
