### ISSUE TITLE
Feature request: Add autoresponders to email list on purchase page for customers

### ISSUE THREAD

**Issue by svendsensvein** [Simplero/Roadmap#73]
At this time Simplero only list broadcasts, not auto responses. 
The purchase screen only shows the content for the product and the "thank you page". 
It would be great for the purchase page to show any auto responder email connected to the product, since a lot of the content/material/information is sent out with these auto responders.

**Comment by calvincorreli** [comment]
I believe we just did that yesterday. If it's not working, please use the HELP link in your account and provide a specific link and details so we can see.
