### ISSUE TITLE
Facebook ecommerce integration and sales tracking

### ISSUE THREAD

**Issue by cipriansoleriu** [Simplero/Roadmap#74]
Hey guys, 
is there a way to track purchases in Facebook similar to what Simplero does with Google Analytics?

Case in point: 
- I have the FB pixel on the order page 
- I send people from FB Ads to the order page in Simplero where I have an order bump or I have an upsell. 
- when people buy they are taken to my custom TY url, off simplero where I track the purchase in Facebook. 
- if ppl buy more products using the upsell or the order bump they are redirected to the same page, so Fb doesn't know that the purchase was 3x the amount of the original TY page purchase.

This means that my ads reporting is wrong since it misses some sales and I'd love to see it receiving all the numbers that simplero crunches when a purchase is made :)

Check this documentation from Fb: https://developers.facebook.com/docs/facebook-pixel/pixel-with-ads/conversion-tracking 

Thanks!

**Comment by cipriansoleriu** [comment]
@calvincorreli any news on this feature? :)

**Comment by christophcemper** [comment]
What is the issue? Passing over the revenue?

In the "third party tracking" you have variables like

{{received_price}}
{{received_tax}}

why not test if these pass over?
@calvincorreli is there a documentation on which variables we can use on custom thank you pages?

**Comment by christophcemper** [comment]
BTW @cipriansoleriu the titel for your issue seems very confusing to me

**Comment by cipriansoleriu** [comment]
@christophcemper

1. Thanks for the idea, haven't tried as when I asked help desk this was not suggested so I assume it's not working 
2. Title seems fine to me but in any case I added the description which helps, hopefully :)

**Comment by calvincorreli** [comment]
@christophcemper they're all right there in the drop-down:

![Screenshot](http://cloud.smpl.ro/0k2B0X3c0L2d/Screen%20Shot%202018-02-03%20at%202.10.27%20PM.png)

**Comment by christophcemper** [comment]
Hey @calvincorreli these I know and love (internal product name converted to url-format would be helpful - i.e. my-product-something

But I think what the need was to pass THOSE parameters to the custom thanks page.
Or is that what you suggested?

**Comment by calvincorreli** [comment]
I misunderstood the original request.

What's preventing you from using the thank you page on Simplero?

**Comment by christophcemper** [comment]
For me it is using all the assets and designs we have in our main website + cookies + user tracking 
e.g. https://www.linkresearchtools.com/thanks/online-resources/?first=Calvin

**Comment by christophcemper** [comment]
No point in duplicating that in our sales backend Calvin, what simplero is. We also have all the sales landing pages on our main CMS

**Comment by calvincorreli** [comment]
If you have both custom tracking code and a custom thank you page, it'll serve a page with the tracking code before redirecting to the final thank you page. That way, tracking should still happen. Does that solve it for you?

**Comment by christophcemper** [comment]
Oh that is some interesting approach - I like it- I cannot speak for Ciprian, but I  believe that would keep A LOT of tracking "hidden" because of that redirect. That's kind of smart, too because then all purchase related (initiate and complete) would be one domain, too - which makes it easier in any case.

**Comment by calvincorreli** [comment]
This is how it's worked for years. I'll add that info to the UI, as it's not obvious.

**Comment by cipriansoleriu** [comment]
@calvincorreli this is great.
How does it work for one click upsells where they click YES and purchase the upsell too?

**Comment by calvincorreli** [comment]
It doesn't actually include upsells and order bumps. Let me fix that so it runs the tracking code for each purchase.

And then that should fix this issue, right?

**Comment by cipriansoleriu** [comment]
@calvincorreli did you fix it to include order bumps/upsells? all good to go now? :)

**Comment by calvincorreli** [comment]
It's deployed now, yes. It'll run the code for each purchase, one after the other, as they can have different tracking codes.

Can you verify for me that it works?

I don't have a tracking situation setup where I can test it IRL.
