### ISSUE TITLE
Forum post bug

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#77]
I have a forum with multiple pages, and those pages have sub-pages. 

When I edit a forum post, I am only able to move it to a main page. 

But members are not even allowed to post on main pages! They are only given the options of choosing sub-pages (categories). 

I need to be able to move the posts to the same place where posts can be made by everyone else. My members are always confused about how to use the forum and it doesn't help that the posts are in different places for no explainable reason. 

I have an issue right now where I really need the ability to move forum posts into sub-pages. In the past Calvin has said that tasks can be bumped up if we pay for them to be a priority I am willing to do that here, depending on what the fee would be, of course.

**Comment by calvincorreli** [comment]
Hi Andrea,

We do not support a hierarchy of subpages in a forum, and don't have any plans to. The fact that you were able to create multiple levels is a bug. That wasn't supposed to happen.

–Calvin

**Comment by AndreaSchroeder77** [comment]
I've had it set up this way for years - the subpages are full of my members' discussions. Are you saying this could all be deleted at some point if the bug is fixed?

**Comment by calvincorreli** [comment]
We'd never delete any content, and I don't see why we'd go and change the structure you have, but it might not work the way you want it to, and you might want to figure out how to flatten it at some point.
