### ISSUE TITLE
Remove navigation menu on page to create landing page

### ISSUE THREAD

**Issue by markyourlifestyle** [Simplero/Roadmap#83]
I would like to have a setting on pages using the Site-function - to allow the main top navigation Menu (and footer) not to be visible.

Today, there is an option tick-box in the Settings that say: "Hide from main navigation - The page will still be accessible but the link won't show up in the main navigation."

If there could also be a tick-box saying "Hide main navigation (and footer) on page" - that would solve the whole landing page problem on Simplero and make it a super excellent platform! :-D

**Comment by nickbruun** [comment]
Hi Mark,

You're halfway to what I want to do with it. Instead of just being able to hide parts of the page, we're instead going let you use the same features to build landing pages at some point in the relatively near future :)
