### ISSUE TITLE
Add Button Section to Site Builder

### ISSUE THREAD

**Issue by mjeeezey** [Simplero/Roadmap#86]
Would be super helpful to be able to add a "button section" instead of having to add content to a different section. Use: add buttons through out website linking to products etc. 

To add a button currently you have to add an image. (Hope I'm missing something :) 

<img width="816" alt="screen shot 2017-07-29 at 9 43 11 pm" src="https://user-images.githubusercontent.com/30561731/28749957-f495a4fe-74a6-11e7-8f84-49657487c153.png">

<img width="335" alt="screen shot 2017-07-29 at 9 42 32 pm" src="https://user-images.githubusercontent.com/30561731/28749951-dd4aad76-74a6-11e7-9809-59587981c6c5.png">

**Comment by nickbruun** [comment]
So, would you want it to be just buttons, or would you want to be able to write text about it too?

**Comment by mjeeezey** [comment]
Editable:
Button Text
Button Link
Button Design (Color, Shape)
Alignment

**Comment by nickbruun** [comment]
This has now been added.

**Comment by mjeeezey** [comment]
Awesome thanks!
