### ISSUE TITLE
Trigger / Automation Based on Last Transaction 

### ISSUE THREAD

**Issue by mjeeezey** [Simplero/Roadmap#87]
Would be awesome to be able to move someone from one list to another based on when their last transaction was. 

My purpose is to be able to automate the continued auto-publishing of content to canceled subscribers who payed for 1-4 more weeks of auto publishing content.

**Comment by calvincorreli** [comment]
Can you explain that more?

So they canceled, but you want them to keep getting content?

Is this a subscription on a product? are you aware that they can cancel to the end of their current period?

**Comment by mjeeezey** [comment]
Subscription to a meal plan / recipe service that releases new content weekly. When the subscriber cancels we would like them to retain access to the content that was "auto-published" to the space while they were a paying subscriber. 

Thanks for the reply!

**Comment by calvincorreli** [comment]
If you grant access to the contact and not the participant, then they'll retain access after the subscription ends. The way you could do that is via a tag. Have the trigger on the product add a tag, then a trigger on the tag grants access to the space or page within the space.

Use the HELP link if you need help setting it up.
