### ISSUE TITLE
Feature request: Full Feature forum

### ISSUE THREAD

**Issue by AndreaSchroeder77** [Simplero/Roadmap#9]
It's very difficult to have a true membership site without a forum and this is the only complaint I get about my Simplero Space.

I would love to see something like Vanilla Forums (their forum features are [here](https://vanillaforums.com/en/features/forums/))

The Simplero forums are really just posts and comments on posts.  Most forums also include other features that help people really engage and feel a part of the community. So features to help with that, like:

- private messaging
- being able to tag each other
- better notifications on new posts (I know you have done some work on that, my participants still find it confusing the way the notifications are not updated upon refresh the way they are on other platforms - plus notifications do not work on some older threads)
- being able to style their own posts (like change font colours) - my members are still commenting on how they miss that feature which Simplero used to have
- having their own "signature" which appears at the bottom of their posts
- the "smart history" feature on the Vanilla page would help - some of my members get lost a lot and have a hard time keeping up with conversations in the space which makes it harder for them to feel a part of the community

Also more editing options like:

- making certain posts sticky
- editing posts including splitting posts and being able to move posts across categories

**Comment by CoachWouter** [comment]
Strongly support this! It will move Simplero closer to being a leading membership site that focuses on the quality and experience of client learning and their results.

**Comment by nickbruun** [comment]
Hi @AndreaSchroeder77,

Could you elaborate further on some of these?

- Being able to tag each other: Do you mean being able to mention eachother by name?
- Better notifications – can you elaborate on this? I'm not sure I understand what you're asking for here
- How does the "smart history" work?

**Comment by AndreaSchroeder77** [comment]
Tagging: when you mention the person by name they get a notification. I think you usually do @Name to make the tag work. 

The "new" icon shows up on new forum posts but then does not disappear when the post has been read - it disappears within a day I think. This makes it very hard to have a conversation then - you don't really know when there is a new post if you are an active user. And I really want to encourage my active members to be able to connect more!

Also when older threads are commented on they don't get bumped up to the top and don't show up on the front page under latest posts - so people try to join a conversation but no one knows so no one ever responds. 

 The Smart History is from Vanilla forums which, from an end-user perspective are ideal forums.  Their features are listed here:  https://vanillaforums.com/en/features/forums/

"Smart History

Vanilla remembers everything you’ve seen, always keeping you up to date with which discussions have new content. Forget about remembering which page you were on, Vanilla puts you right where you stopped reading the last time you were in a discussion."

My members really do have a difficult time following conversations at times.

**Comment by nickbruun** [comment]
@AndreaSchroeder77 thanks. I'm with you in so far as what the feature page says. I just have no idea what "Vanilla puts you right where you stopped reading the last time you were in a discussion" means?

**Comment by AndreaSchroeder77** [comment]
I think that means it brings you to the place on the page where you were when you were reading that post last. To go into an active thread can be confusing, not knowing which posts you have read and which you have not.

**Comment by nickbruun** [comment]
@AndreaSchroeder77 so this is not a feature you've used?

**Comment by AndreaSchroeder77** [comment]
I'm not sure actually. I used to use Vanilla and my members has a much easier time using the forum then and I didn't get as many questions and complaints as I do with the Simplero forum. 

One of the recurring comments is that people can't find where they were in an active thread, and end up giving up trying to participate - which is exactly what this feature would solve.

**Comment by CoachWouter** [comment]
Hi Nick,
Thanks for looping me in. I read that the IPS Board forum (now IPS
community suite 4) also has such a feature to remember what members have
already read and show them new stuff. (And, on another note, readers also
experience this when they use Kindle on multiple devices - it syncs to the
last page read).
Cheers
Wouter

**Comment by calvincorreli** [comment]
Going to close this as it's become unwieldy. File individual feature requests for anything still missing.
