### ISSUE TITLE
Removal of sold out upsells

### ISSUE THREAD

**Issue by KirkRonler** [Simplero/Roadmap#95]
Hi Simplero, 
Quoestion/Request: 
I have some different events; speeches and dance events, that have a limited amount of seats. 
I use these events as upsells. 

Would it be possible to ensure, that when an event is sold out, it will not appear as an upsell either? 

I look forward to hear from you. 

Regards,
An enthusiastic Simplero user :) 

Kirk

**Comment by calvincorreli** [comment]
This makes perfect sense. We should get that done.

**Comment by calvincorreli** [comment]
Will get this deployed this week.
