### ISSUE TITLE
add a RETURN TO TOP button to spaces pages

### ISSUE THREAD

**Issue by teresa-slp** [Simplero/Roadmap#99]
The option to add a RETURN TO TOP button would be a nice feature for some of the longer pages. Especially if we could add one in the middle and one at the comment feed.

**Comment by calvincorreli** [comment]
Not going to happen in spaces.

In membership sites we'll have a theme editor so you can add it yourself.

Or people can hit Cmd-up arrow.

**Comment by teresa-slp** [comment]
okay. thanks!


Yours in sewing, dance and skate,
Teresa Sigmon

founder of Seams Sensational
creator of the Sew Like A Pro™ training series
sewlikeapro.com <https://seamssensational.com/>
